### ISSUE TITLE
Problem with installation BigARTM (MacOS)

### ISSUE THREAD

**Issue by kRUN23** [bigartm/bigartm#1009]
Hello,
I have the problem with installation BigARTM on Mac-OS 
 
I used this instruction
http://docs.bigartm.org/en/stable/installation/linux.html
 
Everything was ok, except for ‘Step 4. Register libartm.dylib’
 
$ echo /usr/local/lib | sudo tee /etc/ld.so.conf.d/artm.conf

tee: /etc/ld.so.conf.d/artm.conf: No such file or directory

/usr/local/lib

 
$ sudo ldconfig

sudo: ldconfig: command not found

 
$ export ARTM_SHARED_LIBRARY=/usr/local/lib/libartm.dylib

 
$ python

Python 2.7.17 |Anaconda, Inc.| (default, Oct 21 2019, 14:10:59) 

[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin

Type "help", "copyright", "credits" or "license" for more information.

>>> import artm

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

ImportError: No module named artm

 
Please, help — How can I solve this problem?
 
OS:
macOS 10.15.4 (19E287)
Kernel: Darwin 19.4.0

 
Regards,
Nikolay Chinnov

**Comment by bt2901** [comment]
Hello,

macOS does seem problematic, as far as installation is concerned. Similar problems were reported before, but I do not know how to fix them.

However, I can suggest a different approach. I have some propositional wheel files for Mac, do you mind testing any of them? There are three files corresponding to python 3.6, 3.7, and 3.8:

https://westbucket4bt.s3-us-west-1.amazonaws.com/bt2901/bigartm/172/172.2/bigartm-0.9.2-cp36-cp36m-macosx_10_13_x86_64.whl
https://westbucket4bt.s3-us-west-1.amazonaws.com/bt2901/bigartm/172/172.2/bigartm-0.9.2-cp37-cp37m-macosx_10_13_x86_64.whl
https://westbucket4bt.s3-us-west-1.amazonaws.com/bt2901/bigartm/172/172.2/bigartm-0.9.2-cp38-cp38-macosx_10_13_x86_64.whl

After downloading, run `pip install <name of file>.whl` and it will hopefully work (to check, run: `python -c "import artm; print(artm.version()); print(artm.ARTM(num_topics=10).info)"`.

**Comment by kRUN23** [comment]
> Hello,
> 
> macOS does seem problematic, as far as installation is concerned. Similar problems were reported before, but I do not know how to fix them.
> 
> However, I can suggest a different approach. I have some propositional wheel files for Mac, do you mind testing any of them? There are three files corresponding to python 3.6, 3.7, and 3.8:
> 
> https://westbucket4bt.s3-us-west-1.amazonaws.com/bt2901/bigartm/172/172.2/bigartm-0.9.2-cp36-cp36m-macosx_10_13_x86_64.whl
> https://westbucket4bt.s3-us-west-1.amazonaws.com/bt2901/bigartm/172/172.2/bigartm-0.9.2-cp37-cp37m-macosx_10_13_x86_64.whl
> https://westbucket4bt.s3-us-west-1.amazonaws.com/bt2901/bigartm/172/172.2/bigartm-0.9.2-cp38-cp38-macosx_10_13_x86_64.whl
> 
> After downloading, run `pip install <name of file>.whl` and it will hopefully work (to check, run: `python -c "import artm; print(artm.version()); print(artm.ARTM(num_topics=10).info)"`.

**Comment by kRUN23** [comment]
Hello, @bt2901 !
Thanks for help.
I did your instructions, but unfortunately I have new error:

$ python -c "import artm; print(artm.version()); print(artm.ARTM(num_topics=10).info)"

INTEL MKL ERROR: dlopen(/Users/krun4ee/opt/anaconda3/lib/libmkl_intel_thread.dylib, 9): Library not loaded: @rpath/libiomp5.dylib
  Referenced from: /Users/krun4ee/opt/anaconda3/lib/libmkl_intel_thread.dylib
  Reason: image not found.
Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.dylib.

Do you know this error too?

Regards,
Nikolay Chinnov

**Comment by bt2901** [comment]
This is a weird error, likely related to conda installation. Could you confirm that `python -c 'import sklearn.linear_model.tests.test_randomized_l1'` (from https://stackoverflow.com/questions/36659453/intel-mkl-fatal-error-cannot-load-libmkl-avx2-so-or-libmkl-def-so) does not work as well?

I looked into it, there are some solutions offered on the web.

1) from https://github.com/BVLC/caffe/issues/3884:
It is suggested to either install/reinstall `nomkl` (Note: `conda install nomkl` means: "Remove `mkl` and replace by a (slow) standard version")

Or to export `LD_PRELOAD` environment variable.

2) from https://software.intel.com/pt-br/forums/intel-fortran-compiler/topic/269694:

I think the trick is to find `libiomp5.dylib` and then run `export DYLD_LIBRARY_PATH=<...>`

The somewhat relevant discussion [here](https://github.com/JuliaPy/PyPlot.jl/issues/315) suggest doing somewhat similar with `LD_LIBRARY_PATH` 

3) As a last resort, could you try updating conda, `conda update numpy` and/or `brew install boost`?

**Comment by kRUN23** [comment]
Thank you, @bt2901 !

It helps with MKL error:
conda remove mkl mkl-service
conda install nomkl numpy scipy scikit-learn numexpr 

Now it works:
python -c "import artm; print(artm.version()); print(artm.ARTM(num_topics=10).info)
