### ISSUE TITLE
Pip

### ISSUE THREAD

**Issue by N1ke72** [bigartm/bigartm#1010]
Здравствуйте. При попытке установить через pip выходит следующая ошибка
"ERROR: Could not find a version that satisfies the requirement bigartm (from versions: none)
ERROR: No matching distribution found for bigartm"
Пробовал на обоих компьютерах. Подскажите, пожалуйста, как можно установить.

**Comment by bt2901** [comment]
А что за ОС? пока что pip поддерживается только на Линуксе, хотя идет
работа по установке на Мак (есть экспериментальные колеса)

вт, 19 мая 2020 г., 12:45 N1ke72 <notifications@github.com>:
