### ISSUE TITLE
Can't install BigARTM on Mac OS 

### ISSUE THREAD

**Issue by EgoVed** [bigartm/bigartm#1031]
Hi!
I haven't been able to install BigARTM for a week. I do everything according to the instructions as indicated here: [https://bigartm.readthedocs.io/en/stable/installation/linux.html#](url)
Everything went well until the Step 4. Register libartm.so / libartm.dylib
in terminal i see an image :
<img width="757" alt="Снимок экрана 2020-10-20 в 20 37 03" src="https://user-images.githubusercontent.com/62134529/96623424-0808cc00-1314-11eb-9027-e89c2318e8c8.png">

Error:tee: /etc/ld.so.conf.d/artm.conf: No such file or directory
/usr/local/lib

Please, help me! What I did wrong?

**Comment by bt2901** [comment]
We have provisional pre-built wheel files for Mac on PyPi. I suggest installing the library with pip: ```pip install -i https://test.pypi.org/simple/ bigartm``` (and this problem will hopefully be fixed here; I'm still gathering feedback about this).

If I am wrong and this issue still persists while installing pre-built wheel, or for some reason installation with pip isn't ideal for you (or doesn't work), we can look into this closer.

**Comment by EgoVed** [comment]
Everything worked out!
Thank you
