### ISSUE TITLE
Predict in BigArtm

### ISSUE THREAD

**Issue by EgoVed** [bigartm/bigartm#1040]
Good afternoon! Tell me please. I only recently started to deal with BigArtm, I'm sorry if the question seems stupid to you. I have a trained bigartm model based on a bag of words. I end up with a prediction of the topics in the document and keywords. And is it possible, when a new document appears, to find out the probability of getting this document to a particular topic on an already deleted model, i.e. not to train the model again . Well, something like the predict function for learning with a teacher.

**Comment by MelLain** [comment]
Hi, look at transform function of ARTM class (in docs)-- Sent from Yandex.Mail for mobile7:21 PM, December 25, 2020, Egor Vedernikov <notifications@github.com>:
Good afternoon! Tell me please. I only recently started to deal with BigArtm, I'm sorry if the question seems stupid to you. I have a trained bigartm model based on a bag of words. I end up with a prediction of the topics in the document and keywords. And is it possible, when a new document appears, to find out the probability of getting this document to a particular topic on an already deleted model, i.e. not to train the model again . Well, something like the predict function for learning with a teacher.

**Comment by EgoVed** [comment]
Thank you!
