### ISSUE TITLE
Missing artm.dll on windows installation

### ISSUE THREAD

**Issue by sequoiarose** [bigartm/bigartm#1043]
It seems the artm.dll file is not being created upon installation. I was able to install the package (downloaded binaries from github, ran `python setup.py build` , `python setup.py install` ) and can `import artm` in a python script. 

Now when I try to run code actually using anything from the package (the batch vector is the first object in my code and where the error propagates from) I am getting an error about the artm.dll file (see attachment). 
<img width="749" alt="artm error" src="https://user-images.githubusercontent.com/63666909/105431670-ebc64500-5c0a-11eb-92bd-93487704527e.PNG">

When I look through the files I have, the artm.dll file is nowhere on my computer. I ran  `python setup.py test` and also received errors about the DLL file, which I cannot replicate right now because the `test` is no longer running any tests (see attachment). It did recommend uninstalling/reinstalling numpy and had an error regarding mlk-service.
<img width="664" alt="artm test" src="https://user-images.githubusercontent.com/63666909/105431671-ebc64500-5c0a-11eb-996d-a02a41e0f0be.PNG">

Do you have any suggestions on how to fix this issue and what may be going wrong? 

I will keep working on trying to fix it, but I am at a loss. So far I have tried updating numpy, mlk-service, checked my python paths, and am getting the same results for both v 0.9.2 and 0.10.1

**Comment by leweex95** [comment]
This issue still persists - disappointing!

**Comment by Omebka** [comment]
I join the question. I have the same problem

**Comment by Omebka** [comment]
> Do you have any suggestions on how to fix this issue and what may be going wrong?

> This issue still persists - disappointing!

I had the same issue. But I found the solution!

Yes, there's no artm.dll in the v.0.10.1. But it's in the v.0.9.0! (It's in the version that has the 'downloads' button?)
You must download this version by clicking 'downloads' button next to the version here - https://github.com/bigartm/bigartm/tags.
Take the 'bin' folder from there and paste it to your BigARTM folder. Add the dll-file (bigartm/bin/artm.dll) to the system variable ARTM_SHARED_LIBRARY.

Don't forget to add paths in your python interpreter (I use PyCharm) to:
bigartm/python
protobuf/python
bigartm/bin/artm.dll (I don't know about the dll-file though, I didn't check it. But it'd better be there)

Reboot your computer!

**Comment by MelLain** [comment]
Hi, since 0.9.0 bigartm doesn't support windows, only osx and linux. As it was mentioned, 0.9.0 can be used for windows users, the difference between versions is minor.
