### ISSUE TITLE
Could not create logging file: No such process

### ISSUE THREAD

**Issue by sashafrey** [bigartm/bigartm#113]
Copied from https://github.com/bigartm/bigartm/issues/111:

> sometimes I have an error on my screen with logging:
> 'Could not create logging file: No such process
> COULD NOT CREATE A LOGGINGFILE 20150205-205823.2054!'
> But this file is created.

I've also seen this issue. It happens inside glog (Logging library for C++ from Google). I'm sure there are ways to solve this, but I have to debug their code to find out. Let me know if this is critical, otherwise I'll just keep this ticket as a reminder and eventually it will be fixed (but not next month).

**Comment by doykov** [comment]
Logging is not critical for me. 
I've just noticed this strange messages:)

**Comment by sashafrey** [comment]
This issue is still happening. I believe it is important to figure out what is wrong with logging because it is essential tool for debugging and diagnostics.

**Comment by ofrei** [comment]
The problem still occurs (for example in bigartm CLI). I didn't figure out exactly when this happens, so the problem require some further investigation. Error message looks as follows:
```
Could not create logging fil
COULD NOT CREATE A LOGGINGFILE 20161117-120411.16268!
```
