### ISSUE TITLE
Specify class_id in cpp_client

### ISSUE THREAD

**Issue by sashafrey** [bigartm/bigartm#121]
cpp_client should allow user to provide list of class_id(s) to tune topic model.

**Comment by sashafrey** [comment]
Few other ideas for cpp_client
-I option for inner_iters_count
-b option for batch folder
-regularize_after after how many documents (iterations?) to start  regularization

**Comment by bigartm** [comment]
Fixed by https://github.com/bigartm/bigartm/pull/161
