### ISSUE TITLE
cpp_client should clean temporary folder with batches after run

### ISSUE THREAD

**Issue by sashafrey** [bigartm/bigartm#140]
Currently cpp_client will fail on a second attempt to run:

cpp_client.exe -v ../python/docword.kos.txt -d ../python/vocab.kos.txt
(works)
cpp_client.exe -v ../python/docword.kos.txt -d ../python/vocab.kos.txt
The directory is not empty: batches

It may confuse BigARTM users.

A better behavior is to
1) without --batches flag to output batches into a temporary folder, and clean it after run
2) with --batches flag reuse batches from the specified folder (or parse collection if -d and -v are provided). In this case folder must not be cleaned after running cpp_client!

**Comment by bigartm** [comment]
Fixed by https://github.com/bigartm/bigartm/commit/a4111173d9f65ffb9ed5e07bc1407557af40794b
