### ISSUE TITLE
Implement UCI bag-of-words collection parser from Python

### ISSUE THREAD

**Issue by sashafrey** [bigartm/bigartm#147]
Parser in C++ is not able to handle non-ASCII characters. The only way to pass in Russian characters is create batches from Python using UTF-8 encoding. For most users this is quite complicated, as they simply want to parse their collection formated as UCI-bag-of-words with non-ASCII vocab file.

A simple solution is to implement parser directly in python interface.

**Comment by bigartm** [comment]
Well.. actually it should be possible to read UTF-8 in Cpp. Let's spend some time and learn how to do it.
http://stackoverflow.com/questions/148403/utf8-to-from-wide-char-conversion-in-stl
http://www.codeproject.com/Articles/38242/Reading-UTF-with-C-streams
http://www.joelonsoftware.com/articles/Unicode.html

**Comment by sashafrey** [comment]
This ticket is not valid. BigARTM had been able to parce unicode data for a very long time, also from C++. One need to make sure that vocab-file is encoded in UTF-8 (that's protobuf requirement), and otherwise parsing will work just fine.
