### ISSUE TITLE
Slow performance in GetTopicModel

### ISSUE THREAD

**Issue by supcry** [bigartm/bigartm#167]
Выгрузка всей 1ГБ модели (44тыс документов, 250тем, около 600тыс терминов) занимает порядка 10 секунд, но выгрузка её частями по 100+100+50тем - более 8 минут.

**Comment by bigartm** [comment]
Performance of dense matrix retrieval was fixed as part of https://github.com/bigartm/bigartm/pull/169
Problem was in many std::find calls to verify if topic had been requested. The code had been rewritten to avoid this problem.
