### ISSUE TITLE
Create Dictionary in ArtmInitializeModel()

### ISSUE THREAD

**Issue by marinadudarenko** [bigartm/bigartm#189]
When we initialize model through model.Initialize() it would be useful to create collection tokens dictionary, for example, as Dictionary object inside MasterComponent. This dictionary could be used for Perplexity calculation or for any other user perpose.

**Comment by sashafrey** [comment]
I'll use this ticket as a master for various enhancements in BigARTM dictionaries. Below I'm copying an e-mail in Russian that describes several important thoughts. 

Текущие возможности работы со словарём
- Операция ``ArtmParseCollection`` (из c_interface) сканирует текстовые файлы в разных форматах и создает батчи. КРОМЕ ЭТОГО, она умеет создать dictionary-файл и сохранить его на диск; также она умеет составлять словарь совместной (попарной) встречаемости слов в текстах.
- Операция ``ArtmInitializeModel`` умеет (1) инициализировать модель с помощью словаря, либо (2)  инициализировать модель просканировав папку с батчами с одновременной фильрацией редких/частых токенов.
- Операция ``ArtmLoadDictionary`` загружает .dictinoary-файл с диска, и возвращает python-коду объект "DictionaryConfig" как protobuf-сообщение. Оно содержащее словарь.
- Операция ``ArtmCreateDictionary`` принимает на вход protobuf-сообщение, содержащее словарь, и загружает его в BigARTM.
- Операция ``ArtmImportDictionary`` загружает словарь с диска в ядро BigARTM

Ограничения
- нет возможности создать словарь, состоящий из уже токенов прошедних частотную фильрацию в ArtmInitializeModel.
- у пользователя нет удобной возможности загрузить свои данные в словарь (есть методы ArtmReconfigureDictionary, но вряд ли кто-то им когда-либо пользовался)

Предложение
- Сделать новую операцию (предлагаю имя ArtmInitializeDictionary), которая принимает на вход папку с батчами и параметры частотной фильтации, и создаёт внутри BigARTM словарь (не сохраняя его на диск). Эта функциональность убирается из ArtmParseCollection и ArtmInitializeModel. Теперь парсинг коллекции это парсинг, а инициализация модели требует на вход словарь (никаких батчей, и никакой фильрации!).
- Сделать операцию ArtmExportDictionary как пару к ArtmImportDictionary. Подгрузка словаря может как бы заменяет вызов ArtmInitializeDictionary.
- Сделать операцию ArtmRequestDictionary, которая позволит выгрузить словарь из BigARTM в виде Protobuf-сообщения
- Сделать операцию ArtmUpdateDictionary, которая позволит добавить/удалить записи в словарь. Инкремент к словарю можно передавать в виде того же самого Protobuf-сообщения, которое возвращает ArtmRequestDictionary.

В итоге работа со методы для работы словарём и с тематической моделью получаются довольно похожими:
ArtmInitializeModel <-> ArtmInitializeDictionary
ArtmExportModel <->  ArtmExportDictionary
ArtmImportModel <-> ArtmImportDictionary
ArtmRequestTopicModel <-> ArtmRequestDictionary
ArtmOverwriteTopicModel <-> ArtmUpdateDictionary 
ArtmDisposeModel <-> ArtmDisposeDictionary
(RequestTopicModel можно со временем переименовать в RequestModel; а OverwriteTopicModel -- в UpdateModel;

Операции которые нужно будет со временем удалить:
ArtmCreateModel <-> ArtmCreateDictionary
ArtmReconfigureModel <-> ArtmReconfigureDictionary

Пытаюсь понять
- чего нехватает чтобы работа со словарями было удобной?
- очевидно что работа с моделью очень похожа на работу со словарями; где правильный уровень абстракции? Нужно ли различать эти сущности в c_interface? Нужно ли сделать им общий интерфейс в ядре библиотеки, от которого они наследуются?
- стоит ли смотреть на словарь как на *вектор* токенов, или как на map из token в дополнительную информацию? 
- Какую информацию хотелось бы видеть в словаре? Индекс токена в фи-матрице? df и td токена (token_count и items_count)? Попарная встречаемость токенов? Ввектор длиной число тем для blacklist и whitelist слов  (можно делать внешним регуляризатором)?
- Хотим ли мы применять словарь чтобы задать порядок следования токенов в модели (DensePhiMatrix)?

**Comment by sashafrey** [comment]
This is fixed by #388 .
