### ISSUE TITLE
"python setup.py test" fails for protobuf in Windows release package of BigARTM

### ISSUE THREAD

**Issue by bigartm** [bigartm/bigartm#24]
Some files are missing in Windows release of BigARTM and cause failures of "python setup.py test". This step is optional, but if we doesn't want users to execute it then we should fix the documentation.

**Comment by sashafrey** [comment]
This had been mentioned in the documentation:

http://docs.bigartm.org/en/latest/tutorials/windows_basic.html
"Avoid python setup.py test step, as it produces several confusing errors. Those errors are harmless. For further details about protobuf installation refer to protobuf/python/README."

Closing the ticket.
