### ISSUE TITLE
Parsing fails if last line in cooc.mmro.txt is empty

### ISSUE THREAD

**Issue by sashafrey** [bigartm/bigartm#244]

**Comment by sashafrey** [comment]
The following script fails if last line in cooc.mmro.txt is empty:

parser_config = artm.messages_pb2.CollectionParserConfig()
parser_config.format = 3  # Cooccurrences
parser_config.dictionary_file_name = 'cooc_dictionary'
parser_config.docword_file_path = r'C:\BigARTM_v0.7.1_x64\mmro\cooc.mmro.txt'
parser_config.vocab_file_path = r'C:\BigARTM_v0.7.1_x64\mmro\vocab.mmro.txt'
parser_config.target_folder = r'C:\BigARTM_v0.7.1_x64\mmro\batches'
artm.library.Library().ParseCollection(collection_parser_config = parser_config)

=>

artm.library.InvalidOperationException: InvalidOperation :  Empty pair of tokens at line 1014233, file C:\BigARTM_v0.7.1_x64\mmro\cooc.mmro.txt

**Comment by MelLain** [comment]
Data format of this file doesn't allow empty lines and this not a bag, but a feature of the reading method.

**Comment by sashafrey** [comment]
I agree that empty lines should cause an error while parsing, however the very last line in the file is somewhat special. I'll refer to this question at stackoverflow:
http://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-file

**Why is it recommended to have empty line in the end of file?**
>Many older tools misbehave if the last line of data in a text file is not terminated with a newline or carriage return / new line combination. They ignore that line as it is terminated with ^Z (eof) instead.

I'd like to add that most users will generate cooc file with a code that looks like this:
while (...)
   cooc << first_id << "\t" << second_id << "\t" << cooc_value << "\n"

This always ends the file with "\n", which BigARTM's parser will treat as an extra line.

**Comment by sashafrey** [comment]
Fixed by #245
