### ISSUE TITLE
Setup CI on window via appveyor.com

### ISSUE THREAD

**Issue by sashafrey** [bigartm/bigartm#250]
appveyor.com is a free CI system for Windows. It is configured via appveyor.yml file in the root of the repository, similarly to travis.yml. Check https://github.com/Microsoft/bond for an example of C++ project that uses appveyor.com.

**Comment by sashafrey** [comment]
https://github.com/alex85k/sqlite3-cmake/blob/master/appveyor.yml - that's also a good one

**Comment by sashafrey** [comment]
I've started working on this inhttps://github.com/bigartm/bigartm/pull/252, but it turned out to be quite challenging and we abandoned the task for now.

**Comment by sashafrey** [comment]
@JeanPaulShapo FYI, I think I found a good idea on how to configure Appveyor for Windows -- we just need to take the same approach as VW project. They install all dependencies, including Boost, via `nuget` packages. 
https://github.com/JohnLangford/vowpal_wabbit/tree/master/vowpalwabbit/.nuget
Their appveyor script is here:
https://github.com/JohnLangford/vowpal_wabbit/blob/master/appveyor.yml
I'll try to investigate if we can do the same.

**Comment by ofrei** [comment]
Appveyor is configured. See the history of this file for all information: https://github.com/bigartm/bigartm/blob/master/appveyor.yml
