### ISSUE TITLE
Documentation: rewrite all python examples in C++ 

### ISSUE THREAD

**Issue by bigartm** [bigartm/bigartm#27]
Currently we have nice 8 examples for python, and none for C++ (except for cpp_client, which is our 'internal' stuff we use for testing). It would be nice to re-write all 8 examples from Python into C++ and create a simple walkthrough page in the documentation (similar to the Python tutorial).

**Comment by sashafrey** [comment]
This is not a priority anymore. C++ interface is not used as much as python, and it can stay undocumented for a long time. Therefore we won't make the examples.
