### ISSUE TITLE
Hang in rpcz::application::create_rpc_channel()

### ISSUE THREAD

**Issue by bigartm** [bigartm/bigartm#28]
I've seen that in some cases RPCZ hangs in rpcz::application::create_rpc_channel (call stack below).
We should enhance this method to pass some connection timeout.

 	[External Code]	
 	artm.dll!zmq::signaler_t::wait(int timeout_) Line 209	C++
 	artm.dll!zmq::mailbox_t::recv(zmq::command_t * cmd_, int timeout_) Line 72	C++
 	artm.dll!zmq::socket_base_t::process_commands(int timeout_, bool throttle_) Line 915	C++
 	artm.dll!zmq::socket_base_t::send(zmq::msg_t * msg_, int flags_) Line 736	C++
 	artm.dll!s_sendmsg(zmq::socket_base_t * s_, zmq_msg_t * msg_, int flags_) Line 354	C++
 	artm.dll!rpcz::send_empty_message(zmq::socket_t * socket, int flags) Line 108	C++
 	artm.dll!rpcz::connection_manager::connect(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & endpoint) Line 463	C++
	artm.dll!rpcz::application::create_rpc_channel(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & endpoint) Line 60	C++
 	artm.dll!artm::core::Instance::Reconfigure(const artm::MasterComponentConfig & master_config) Line 335	C++
 	artm.dll!artm::core::Instance::Instance(const artm::MasterComponentConfig & config, artm::core::InstanceType instance_type) Line 80	C++
 	artm.dll!artm::core::NodeControllerServiceImpl::CreateOrReconfigureInstance(const artm::MasterComponentConfig & request, rpcz::reply<artm::core::Void> response) Line 34	C++
 	artm.dll!artm::core::NodeControllerService::call_method(const google::protobuf::MethodDescriptor * method, const google::protobuf::Message & request, rpcz::server_channel * channel) Line 491	C++
 	artm.dll!rpcz::proto_rpc_service::dispatch_request(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & method, const void * payload, unsigned __int64 payload_len, rpcz::server_channel * channel_) Line 136	C++
 	artm.dll!rpcz::server::handle_request(const rpcz::client_connection & connection, rpcz::message_iterator & iter) Line 209	C++
 	artm.dll!rpcz::worker_thread(rpcz::connection_manager * connection_manager, zmq::context_t * context, std::basic_string<char,std::char_traits<char>,std::allocator<char> > endpoint) Line 170	C++
 	artm.dll!boost::detail::thread_data<boost::_bi::bind_t<void,void (__cdecl*)(rpcz::connection_manager * __ptr64,zmq::context_t * __ptr64,std::basic_string<char,std::char_traits<char>,std::allocator<char> >),boost::_bi::list3<boost::_bi::value<rpcz::connection_manager * __ptr64>,boost::_bi::value<zmq::context_t * __ptr64>,boost::_bi::value<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > > > >::run() Line 118	C++
 	[External Code]

**Comment by sashafrey** [comment]
Not applicable because network modus  operandi is removed (=> rpcz is no longer in use)
