### ISSUE TITLE
Meaningless exception when --docword or --vocab file refers to a folder

### ISSUE THREAD

**Issue by sashafrey** [bigartm/bigartm#291]
Reprosteps: use cpp_client or bigartm.exe, and pass in path to any folder as --docword or --vocab file. This  leads to meaningless  exception:

Dynamic exception type: class boost::exception_detail::clone_impl<struct boost::exception_detail::error_info_injector<class std::ios_base::failure> >
std::exception::what: failed opening file: Access is denied.

**Comment by JeanPaulShapo** [comment]
Fixed by #338

**Comment by JeanPaulShapo** [comment]
Closed
