### ISSUE TITLE
Implement MasterModel to expose high level operations in C intrerface

### ISSUE THREAD

**Issue by sashafrey** [bigartm/bigartm#325]
(This is described in Russian as it comes form an internal discussion.)

**ScoreConfig и RegularizerConfig**
This had been moved into a new issue #402

**MasterModel***
Одно из важных решений, принятых в  python-интерфейсе ARTM, в следующем. В рамках этого API каждый MasterComponent в BigARTM содержит только одну модель (возможно из двух матриц - "pwt" и "nwt", но это скрыто от пользователя). Эту идею нужно перенести в ядро, реализовав новую сущность MasterModel - т.е. помесь MasterComponent и ModelConfig.

На уровне C-interface это может выглядеть так (описания входных protobuf-сообщений см. ниже):
```
// возвращает master_id
int ArtmCreateMasterModel(int length, const char* master_model_config);

// позволяет менять состав функционалов качества,
// регуляризаторов, и коэффициенты regularizer_tau и class_weight.
int ArtmReconfigureMasterModel(int master_id, int length,
                               const char* master_model_config);

// одна итерация настройки online-алгоритма
int ArtmFitOnlineMasterModel(int master_id, int lenght,
                             const char* fit_online_master_model_config);

// одна итерация настройки offline-алгоритма
int ArtmFitOfflineMasterModel(int master_id, int lenght,
                              const char* fit_offline_master_model_config);

// применяет модель к данным; should we call this Transform or Apply?
int ArtmRequestTransformMasterModel(int master_id, int length,
                                    const char* transform_master_model_config);
```

С MasterModel очень многие вещи будет делать с помощью уже известных интерфейсных функций:
- выгрузку Theta и Phi матриц
- выгрузку функционалов качества
- import/export модели
- инициализацию модели по словарю или по папке с батчами

Описания protobuf-сообщений:

```
message MasterModelConfig {
  repeated string topic_name
  repeated string topic_set
  repeated string topic_set_size
  repeated string class_id
  repeated float class_weight 
  repeated ScoreConfig score_config;
  repeated RegularizerConfig regularizer_config;
  repeated double regularizer_tau;
  optional bool cache_theta;
  optional int32 threads;
  optional string pwt_name;
  optional string nwt_name;
}

message MasterModelFitArgsOffline {
  repeated string batch_filename;
  repeated float batch_weight
}

message MasterModelFitArgsOnline {
  repeated string batch_filename;
  repeated float batch_weight
  optional int32 inner_iterations_count;
  optional int32 update_every;
  optional int32 tau0;
  optional double kappa;
}

TransformMasterModelArgs {
  repeated string batch_filename;
  Ptdw or Theta?
  Sparse or Dense?
}
```

**Comment by sashafrey** [comment]
``ARTM.py`` выгружает функционалы качества после каждой синхронизации модели, а в предложенном интерфейсе MasterModel логичней считать FitOnline / FitOffline одним проходом по коллекции и выгружать функционалы после окончания прохода. Получается, что MasterModel не в полной мере поможет  упростить код ``ARTM.py``.

**Comment by dselivanov** [comment]
any progress?

**Comment by sashafrey** [comment]
@dselivanov I've started on this and it should be in master by the end of this year. It takes a bit longer because we've spend quite some time re-working dictionaries ( PR #388 )

**Comment by sashafrey** [comment]
@dselivanov This feature is now mostly implemented in PR #401 :

* See class `MasterModel` from [BigARTM C++ interface](https://github.com/sashafrey/bigartm/blob/master_model/src/artm/cpp_interface.h) for the definition of the new API. There are two usage examples - one in the [master_model_test.cc](https://github.com/sashafrey/bigartm/blob/master_model/src/artm_tests/master_model_test.cc), another in [BigARTM CLI](https://github.com/sashafrey/bigartm/blob/master_model/src/bigartm/srcmain.cc). CLI code is quite complicated so I would suggest to look at the test first... 
* Usability enhancement around `ScoreConfig` and `RegularizerConfig` is not included in this pull request, and will be done later
* For now `MasterModel` is not consumed in our python interface (not decided yet on whether we should, for example because of `ScoreTracker` feature in python API)

I'll do some final testing tomorrow and if everything works integrate to master branch.

**Comment by sashafrey** [comment]
Fixed by #401
