### ISSUE TITLE
Rewrite documentation about BigARTM for Linux and Mac OS-X

### ISSUE THREAD

**Issue by JeanPaulShapo** [bigartm/bigartm#386]
Someone who has enough permissions ought to assign label "documentation" to this issue.

**Comment by sashafrey** [comment]
@JeanPaulShapo Could you please add one or two sentences about the planned change? I'm just trying to cleanup the list of our issues, and close those that don't represent any work planned for the future.

**Comment by JeanPaulShapo** [comment]
Fixed by #706.
