### ISSUE TITLE
CentOS linker issue

### ISSUE THREAD

**Issue by dselivanov** [bigartm/bigartm#395]
On CentOS 7 I got following:
> [ 99%] Building CXX object src/bigartm/CMakeFiles/bigartm.dir/__/artm/cpp_interface.cc.o
[100%] Building CXX object src/bigartm/CMakeFiles/bigartm.dir/__/artm/messages.pb.cc.o
Linking CXX executable bigartm
/usr/bin/ld: cannot find -lboost_thread-mt
/usr/bin/ld: cannot find -lboost_program_options-mt
/usr/bin/ld: cannot find -lboost_date_time-mt
/usr/bin/ld: cannot find -lboost_filesystem-mt
/usr/bin/ld: cannot find -lboost_iostreams-mt
/usr/bin/ld: cannot find -lboost_system-mt
/usr/bin/ld: cannot find -lboost_chrono-mt
/usr/bin/ld: cannot find -lboost_timer-mt
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lstdc++
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make[2]: *** [src/bigartm/bigartm] Error 1
make[1]: *** [src/bigartm/CMakeFiles/bigartm.dir/all] Error 2
make: *** [all] Error 2

Actually I have all this files, but they start with **lib** instead of **l**.
I'm not make/cmake expert, so can't figure out how to fix this.

**Comment by dselivanov** [comment]
I can manually create symlink, but probably this will be ugly solution.

**Comment by sashafrey** [comment]
@dselivanov bigartm executable by default builds with static linkage. Could you try disable this as follows?
```
cmake -DBUILD_STATIC_BIGARTM=OFF ..
```
(and then build bigartm as usual)

**Comment by dselivanov** [comment]
this helps! thank you. Closing now?

**Comment by sashafrey** [comment]
before closing let's discuss whether we should set static linkage to `OFF` by default.
@romovpa @JeanPaulShapo What do you think? By now we know that static linkage has issues on Mac OS X and Cent OS. To me it sounds like an extra option that users should manually switch ON if they care...
@JeanPaulShapo Recently you implemented `make install` for Linux. Would it still install enough dependencies if we switch static linkage to `OFF` by default?

**Comment by dselivanov** [comment]
Before installing on centos server, I installed bigartm on my Macbook. It
works out of the box without any problems ( with static linkage).
24 дек. 2015 г. 7:44 PM пользователь "sashafrey" <notifications@github.com>
написал:

**Comment by sashafrey** [comment]
Hm.. I'm fairly sure someone reported a similar issue on latest Mac OS X (presumably 10.11.1). Nice to know it worked for you!

**Comment by dselivanov** [comment]
I'm on 10.10 :-) there always issues on new systems :-)
24 дек. 2015 г. 8:06 PM пользователь "sashafrey" <notifications@github.com>
написал:

**Comment by JeanPaulShapo** [comment]
@dselivanov Could you write here all boost-* packages installed on you CentOs 7?

**Comment by JeanPaulShapo** [comment]
@sashafrey As I can see from running `cmake -DBUILD_STATIC_BIGARTM=OFF && make && make install`, it's ok to switch static linkage to `OFF` by default. But let's make decisions after receiving response from @dselivanov.

**Comment by dselivanov** [comment]
@JeanPaulShapo see [here](https://gist.github.com/dselivanov/161815981a03107144ef).

**Comment by JeanPaulShapo** [comment]
@dselivanov Thanks, although I expected to see filtered output from your package manager :) Nevertheless, it's likely that you don't have package `boost-static` installed on your CentOS 7 machine. It contains static analogues for boost dynamic libraries. And the word `static` in the name of the package implies ability for static linkage.
Could you have patience and necessary permisions to install `boost-static` package and run `rm -rf CMakeCahe.txt && cmake ../ && make` to check whether you have the error or not?

**Comment by dselivanov** [comment]
> Linking CXX executable bigartm
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lstdc++
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make[2]: *** [src/bigartm/bigartm] Error 1
make[1]: *** [src/bigartm/CMakeFiles/bigartm.dir/all] Error 2
make: *** [all] Error 2

**Comment by JeanPaulShapo** [comment]
@dselivanov Try to install `glibc-static` and `libstdc++-static`. Hope it works.

**Comment by dselivanov** [comment]
@JeanPaulShapo thx, now it works fine with static linker.

**Comment by JeanPaulShapo** [comment]
@dselivanov Of course, we do need. 
But how do you know that you need boost?
After brief search I did't find any information about requirements (e.g. boost packages) neither in README nor in <a href=docs.bigartm.org>documentation</a>. Am I missing sometihing?

**Comment by dselivanov** [comment]
cmake suggest to install it :-)

2015-12-25 14:47 GMT+03:00 Nikita Shapovalov <notifications@github.com>:

> @dselivanov <https://github.com/dselivanov> Of course, we do need.
> But how do you know that you need boost?
> After brief search I did't find any information about requirements (e.g.
> boost packages) neither in README nor in documentation
> <http://docs.bigartm.org>. Am I missing sometihing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bigartm/bigartm/issues/395#issuecomment-167224671>.
>



-- 
Regards
Dmitriy Selivanov

**Comment by sashafrey** [comment]
@JeanPaulShapo Could you fix this in the documentation and then close this ticket?

**Comment by JeanPaulShapo** [comment]
@dselivanov I think now [instructions](http://docs.bigartm.org/en/latest/installation/linux.html) looks OK. Check them and tell us, whether to close this issue or not? :-)

**Comment by dselivanov** [comment]
looks ok for me! sorry for the long response.
