### ISSUE TITLE
ThetaScore overflow on large collection due to int32 limit

### ISSUE THREAD

**Issue by dselivanov** [bigartm/bigartm#413]
On collection of 17M documents I got negative `SparsityTheta` measure. Probably `int` overflow:

> \> ./bigartm --topics "topic:200,noise:3" --use-dictionary ~/projects/artm/data/dict.dict --use-batches ~/projects/artm/data/artm_batches --async --threads 16 --regularizer "0.5 smoothPhi #noise*" --regularizer "0.5 sparsePhi #topic*" --regularizer "0.5 smoothTheta #noise*" --regularizer  
 "0.5 sparseTheta #topic*" --regularizer "1000 decorrelation #topic*" --passes 1  --update-every 5 --save-model v2.model --write-model-readable msg_200topics_3noise.phi.txt
Using 1472 batches from '/home/dmitry.selivanov/projects/artm/data/artm_batches'
Loading dictionary file from /home/dmitry.selivanov/projects/artm/data/dict.dict... OK.
Initializing random model from dictionary... OK.
Number of tokens in the model: 294830
================= Processing started.
W0106 21:59:56.761248  7642 master_component.cc:529] Model NWT does not exist
Perplexity      = 4852.25
SparsityPhi     = 0.233727
SparsityTheta   = -0.614745
================= Iteration 1 took  2363490 milliseconds.

**Comment by sashafrey** [comment]
I hope this is fixed by #414 . Could you please pull latest master and verify whether `ThetaScore` no longer have negative values?

**Comment by dselivanov** [comment]
Resolved!
> Number of tokens in the model: 294830
================= Processing started.
Perplexity      = 273770
SparsityPhi     = 4.2272e-06
SparsityTheta   = 0.00389507
================= Iteration 1 took 185787
Perplexity      = 20272
SparsityPhi     = 6.64155e-05
SparsityTheta   = 0.0142307
================= Iteration 2 took 185535
Perplexity      = 8311.51
SparsityPhi     = 0.031639
SparsityTheta   = 0.225129
================= Iteration 3 took 185876
