### ISSUE TITLE
Upgrade to proto3

### ISSUE THREAD

**Issue by sashafrey** [bigartm/bigartm#415]
proto3 has nice features such as serializing messages to/from JSON. This will make it even easier to use BigARTM API, because then clients will be able to avoid the dependency on protobuf. 
https://developers.google.com/protocol-buffers/docs/proto3?hl=en#json

**Comment by sashafrey** [comment]
@JeanPaulShapo  Hi, is this something you would be interested to look at?

**Comment by dselivanov** [comment]
it would be very nice if `bigartm` will use system protobuf library instead of supplied one.

**Comment by sashafrey** [comment]
@dselivanov I agree. Could you please open a separate ticket for it, as it might be done independent from proto3 upgrade. Also, using a system protobuf can be added as an extra option - not as a replacement for the protobuf supplied with BigARTM. My gut feeling is that on Windows protobuf must be build together with BigARTM because installing it separately will cause too much trouble for the users.

**Comment by dselivanov** [comment]
see #420

**Comment by JeanPaulShapo** [comment]
@sashafrey Is it ok to close this ticket?
