### ISSUE TITLE
Warn about D, W, NNZ when parsing UCI BOW format

### ISSUE THREAD

**Issue by sashafrey** [bigartm/bigartm#423]
UCI bow format starts with three integer values (`D`, `W` and `NNZ`), which are currently ignored by BigARTM. The values needs to be there according to UCI bow format, but if users don't provide them then it will appears that the library just ignores the first triple `(doc_id, word_id, tf)`.
BigARTM should at least issue a warning when first three values (treated as `D`, `W` and `NNZ`) are inconsistent with the remaining content of the docword file.

**Comment by AnyaP** [comment]
Does it mean that as a user I can provide 0, 0, 0 as the first three lines and be fine with it?

**Comment by sashafrey** [comment]
@AnyaP Sorry, I missed your question. The answer is YES.

**Comment by JeanPaulShapo** [comment]
OFFTOPIC: @sashafrey Could you comment necessity of supporting '%' in UCI BoW docword format? During investigating this issue I came across failures of tellg() and seekg() (e.g. with std::cin).

**Comment by ofrei** [comment]
@JeanPaulShapo The idea was to support matrix market format:
http://math.nist.gov/MatrixMarket/formats.html
This is essentially the same as UCI BOW, except that it can start with some sort of header where lines are commented out by ``%`` character.

**Comment by ofrei** [comment]
I think it is nice to support this format because it is also supported in gensim (https://radimrehurek.com/gensim/corpora/mmcorpus.html). 

Is there a better way of skipping all lines starting with % ?4
