### ISSUE TITLE
batch format

### ISSUE THREAD

**Issue by dselivanov** [bigartm/bigartm#424]
I'm trying to create wrapper for `ArtmAddBatch`. Here is my message:
```
token: "a"
token: "b"
token: "c"
class_id: "1"
class_id: "1"
class_id: "1"
item {
  id: 1
  field {
    name: "fld_name"
    token_id: 1
    token_id: 2
    token_id: 3
    token_offset: 1
    token_offset: 2
    token_offset: 3
    token_weight: 1
    token_weight: 2
    token_weight: 3
  }
  title: "title"
}
```
But when I call `ArtmAddBatch` it always returns `-5` - corrupted message. I'm using protobuf 2.5.0 (not beta) on client side.

**Comment by sashafrey** [comment]
You may use  ArtmGetLastErrorMessage to fetch full error status. I'm
guessing in this case is because there is batch.id field is not set or it
is not formatted as GUID:
00000000-0000-0000-0000-000000000000

On Tue, Jan 19, 2016 at 1:53 PM, Dmitriy Selivanov <notifications@github.com

**Comment by dselivanov** [comment]
I missed it in my message, but actually I have it:
```
token: "a"
token: "b"
token: "c"
class_id: "1"
class_id: "1"
class_id: "1"
item {
  id: 1
  field {
    name: "fld_name"
    token_id: 1
    token_id: 2
    token_id: 3
    token_offset: 1
    token_offset: 2
    token_offset: 3
    token_weight: 1
    token_weight: 2
    token_weight: 3
  }
  title: "title"
}
description: "ff"
id: "A5C89FD5-5936-4BF7-9DF7-11F99A107618"
```
Error produced by `ArtmGetLastErrorMessage ` is following: 
> "CorruptedMessageException :  Unable to parse the message"`

**Comment by sashafrey** [comment]
Have you generated the message in `R`? Could you please send me the binary buffer - its length and the actual bytes that you are sending into BigARTM. I'll try to look into it.. Google protobuf format is quite simple so its possible to decode it manually :)
https://developers.google.com/protocol-buffers/docs/encoding?hl=en

We can also look into adding an option to pick system-installed Protobuf, or to upgrade BigARTM to Protobuf v3.0 so that you could sent JSON.

**Comment by dselivanov** [comment]
Yes, I serialize them in R. Here is my 113 bytes:
```
0a 01 61 0a 01 62 0a 01 63 12 01 31 12 01 31 12 01 31 1a 33 08 01 12 28 0a 08 66 6c 64 5f 6e 61 6d 65 10 01 10 02 10 03 20 01 20 02 20 03 a5 01 00 00 80 3f a5 01 00 00 00 40 a5 01 00 00 40 40 1a 05 74 69 74 6c 65 22 02 66 66 2a 24 37 44 38 46 42 44 44 45 2d 30 41 46 42 2d 34 41 39 30 2d 42 35 32 35 2d 39 36 33 37 45 38 45 37 34 39 30 38
```
Have no problems with another messages - dictionary config, master config, etc.
Don't think that json is good idea for such big messages as batches can be.

**Comment by sashafrey** [comment]
Ah... Now I see the problem. `ArtmAddBatch` accepts `AddBatchArgs` message, not `Batch`. I know this should be in the documentation, but for now you may check `c_interface.cc` file, for example: https://github.com/bigartm/bigartm/blob/master/src/artm/c_interface.cc#L159

**However**, I would strongly recommend to use another API -- `ArtmImportBatch` (which accepts `ImportBatchesArgs`). The `AddBatchArgs` is legacy and will be removed very soon. If you would like to pass batches through memory and then use them in `ArtmFit[Online|Offline]MasterModel` then the `ImportBatchesArsg`, then `ArtmimportBatch` is the way to go. 

I see that it might be confusing that in `ImportBatchesArgs` you need to specify batch name. Perhaps I should remove this field, and always use `Batch.id` as identifier. But for now you should copy `Batch.id` into `ImportBatchesArgs.batch_name`. Then `FitOnlineMasterModelArgs.batch_filename` can also list the same names. E.g. it does not have to be a filename. The `batch_name` of previously imported batches are also supported in `FitOnlineMasterModelArgs`, `FitOfflineMasterModelArgs` and `TransformMasterModelArgs`.



The batch was correctly formatted and I've been able to parse it via the following C++ code snippet:
```
std::string hexToBytes(const std::string& input) {
  std::string retval;
  retval.resize(input.length() / 3);  // expects the input to end with ' ' (space)
  char* buffer = &*retval.begin();

  for (int i = 0; i < input.size(); i += 3) {
    std::stringstream hexBuffer;
    hexBuffer << std::hex << input[i] << input[i + 1];
    unsigned int value;
    hexBuffer >> value;
    buffer[i / 3] = value;
  }
  return retval;
}

// To run this particular test:
// artm_tests.exe --gtest_filter=Messages.ParseBatch
TEST(Messages, ParseBatch) {
  std::string msg("0a 01 61 0a 01 62 0a 01 63 12 01 31 12 01 31 12 01 31 1a 33 08 01 12 28 0a 08 66 6c 64 5f 6e 61 6d 65 10 01 10 02 10 03 20 01 20 02 20 03 a5 01 00 00 80 3f a5 01 00 00 00 40 a5 01 00 00 40 40 1a 05 74 69 74 6c 65 22 02 66 66 2a 24 37 44 38 46 42 44 44 45 2d 30 41 46 42 2d 34 41 39 30 2d 42 35 32 35 2d 39 36 33 37 45 38 45 37 34 39 30 38 ");
  std::string bytes = hexToBytes(msg);
  ASSERT_EQ(bytes.size(), 113);

  ::artm::Batch batch;
  batch.ParseFromArray(bytes.c_str(), bytes.size());
}
```

**Comment by sashafrey** [comment]
@dselivanov Did this solve the issue? Let me know if it is OK to close the ticket.

**Comment by dselivanov** [comment]
Still haven't chance to try :-(

2016-01-24 19:21 GMT+03:00 sashafrey <notifications@github.com>:

> @dselivanov <https://github.com/dselivanov> Did this solve the issue? Let
> me know if it is OK to close the ticket.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bigartm/bigartm/issues/424#issuecomment-174312791>.
>



-- 
Regards
Dmitriy Selivanov

**Comment by sashafrey** [comment]
Ok, no problem!

**Comment by sashafrey** [comment]
@dselivanov I'm fairly sure the answer resolves the issue, at least on my machine. Closing the ticket. Feel free to reopen if my solution didn't work, or create a new ticket to start a fresh discussion!
