### ISSUE TITLE
Semi-supervised classification example?

### ISSUE THREAD

**Issue by usptact** [bigartm/bigartm#432]
With the latest BigARTM version it is possible to perform classification if the target modality is shown. In the articles authors mention that it is possible to do learning in semi-supervised setting.

My question is how is it practically done? Should I put the target modality for the labeled documents and omit the target modality for the unlabeled documents?

Thanks

**Comment by sashafrey** [comment]
Yes, classification can predict missing modalities. Here is an example for command-line interface:
```
>bigartm.exe --help
...
* Fit model with two modalities (@default_class and @target), and use it to predict @target:
  bigartm --use-batches <batches> --use-modality @default_class,@target --topics 50
          --passes 10 --save-model model.bin
  bigartm --use-batches <batches> --use-modality @default_class,@target --topics 50
          --load-model model.bin
          --write-predictions pred.txt --csv-separator=tab
          --predict-class @target --write-class-predictions pred_class.txt --score ClassPrecision
```
First command fits the model for two modalities, second command applies it to batches where `@target` label is missing. `--write-class-predictions` will output the most probably label for each item; `--write-predictions` will for each item output a probability distribution across all target labels.

Let me know you need examples with other APIs (C++ or Python).

**Comment by usptact** [comment]
Thanks @sashafrey! 

I understand that this might be a question for a new thread, but by extension - is it possible to have the target modality with multiple labels to predict? Will this work?

**Comment by sashafrey** [comment]
It is OK to have target modality with multiple labels, for example modality `@country` with alternatives `ru`, `en`, `us`. Using `--write-predictions` you will get, for example, a distribution (`0.55, 0.10, 0.35`) -- e.g. `55%` towards `ru`, `10%` towards `en` and the remaining `35%` towards `us`. Then you have to choice on where to put the threshold and how to interpret these probabilities. One option is to pick the most probable label, but alternatively you may choose to return all values above let's say `0.2`  -- then you may get up to 5 target labels (or potentially none, if there are not just 3 but more than 5 countries in the list, and all of them get an equally small probability).
