### ISSUE TITLE
Progress bar for fitting models

### ISSUE THREAD

**Issue by AnyaP** [bigartm/bigartm#447]
When relatively large corpora are used, it's uncertain how long fit_offline() or fit_online() is going to be executed in Python API. It would be really beneficial to see how many Phi updates have been performed so far or how many documents have been processed or any other indicator of progress.

**Comment by sashafrey** [comment]
@AnyaP This is indeed very reasonable request. Would it be sufficient to add progress logging into bigartm log file?.. Perhaps not. I guess for you the most convenient option would be to see progress info in the python log.

**Comment by AnyaP** [comment]
Right, ideally it would be somewhere in ipython-notebook output. But any solution would be better than no progress bar at all :)

**Comment by sashafrey** [comment]
@AnyaP For now I will fix the logging so that it reports how many batches had been processed (somethingl like `123/666 batches had been successfully processed, 0 failures`), for `ArtmFitOfflineMasterModel` and `ArtmFitOnlineMasterModel` methods  (a new low-level APIs intoruced in v0.7.4; see [release notes](http://docs.bigartm.org/en/stable/release_notes/v0.7.4.html) for some detaiils). You will  see this as soon as @MelLain switches python API to `ArtmFit[Offline|Online]MasterModel`.

**Comment by AnyaP** [comment]
Great, thanks!
16 февр. 2016 г. 9:18 пользователь "sashafrey" <notifications@github.com>
написал:

**Comment by AnyaP** [comment]
Hi @sashafrey,
I'm using the latest master version, so I thing I should see these [123/666 batches had been successfully processed, 0 failures] somewhere.

Should it be in log.INFO? For semi-offline algorithm that takes sooo loong, I can see there only something like:

I1213 20:17:49.625349 246452224 merger.cc:127] Merger thread stopped
I1213 20:17:49.625468 2021769984 master_component.cc:48] Disposing MasterComponent (id=23)...
I1213 20:17:49.626739 251281408 processor.cc:957] Processor thread stopped
I1213 20:17:49.626802 251281408 processor.cc:958] Total number of processed batches: 0
I1213 20:17:49.628093 250744832 processor.cc:957] Processor thread stopped
I1213 20:17:49.628156 250744832 processor.cc:958] Total number of processed batches: 0
I1213 20:17:49.629464 250208256 processor.cc:957] Processor thread stopped
I1213 20:17:49.629521 250208256 processor.cc:958] Total number of processed batches: 0
I1213 20:17:49.630810 249671680 processor.cc:957] Processor thread stopped
I1213 20:17:49.630843 249671680 processor.cc:958] Total number of processed batches: 0
I1213 20:17:49.632200 249135104 merger.cc:127] Merger thread stopped

**Comment by sashafrey** [comment]
@AnyaP This is not yet implemented. Thanks for reminder! I'll do that ASAP.

**Comment by sashafrey** [comment]
I've started working on this in PR https://github.com/bigartm/bigartm/pull/476, but it has to wait until v0.8.1. The priority for v0.8.0 is API-breaking change, and this request can be delivered as an incremental change.

**Comment by nadiinchi** [comment]
Is it hard to add verbose parameter to fit_offline and fit_online as in sklearn and print info about model learning process?

**Comment by ofrei** [comment]
Fixed
