### ISSUE TITLE
Please give us your feedback about BigARTM

### ISSUE THREAD

**Issue by sashafrey** [bigartm/bigartm#460]
Hi dear BigARTM stargazers!

@vadimantiy @travisbrady @esafak @sam-splat @IlyaTrofimov @hustwj @usptact @i-Hun @valdas @iinm @skovorodkin @pased @sld @aecio @persiyanov @peterwittek @dselivanov @MadFaill @ivannz @dustalov @nimblemachine @p0123n @Odomontois @alexanderpanchenko @thedrow @kmike @alexeyev @karpnv @rdkl @yazevnul @Barmaley-exe @romovpa @jubbon

First and foremost, thank you so much for staring BigARTM project! Now we have reached an important milestone of ``32`` starts (:star:). The next stations along this journey are at ``64``, ``128``, ``256``, ``512`` and, of course, ``1024`` starts (:star: :star2: :boom:) Could you please help us to reach them by filling in the following short survey:

http://goo.gl/forms/tr5EsPMcL2

You may also leave your feedback in the comments to this issue, or by sending an e-mail to me directly at `s a s h a f r e y AT g m a i l . com`. I'm especially interested to know what are the biggest pain points for you. *Lack of documentation*, *hard to install*, *confusing input formats*, *missing features*, or anything else --- really! Please let us know.

Thanks!
Alex aka @sashafrey
*(on behalf of all BigARTM contributors)*

**Comment by sashafrey** [comment]
We have received and analyzed 12 responses for BigARTM survey that I sent out earlier. I still had to time to summarize the feedback, but I will do my best to include it in v0.8.0 release notes.
Thanks to everyone who participated!

**Comment by usptact** [comment]
@sashafrey Is it possible to take a look at survey responses?

**Comment by sashafrey** [comment]
@usptact I'm not sure how properly share the results from google forms. You may take a look at this spreadsheet:
[BigARTM survey.xlsx](https://github.com/bigartm/bigartm/files/177309/BigARTM.survey.xlsx)
And graphically the results are as follows:
![image](https://cloud.githubusercontent.com/assets/1252606/13837541/987d7c9c-ec0c-11e5-90ff-f682926314a4.png)

**Comment by sashafrey** [comment]
Key takeaways are from the survey are like this:
* Include auto-generated docs for python in the online documentation. Prioritize all other aspects of the documentation.
* Implement `pip install bigartm`
* Ensure that python API is as stable as possible. Prioritize changes in python API over (as the most used one) versus the other APIs such as C++, CLI, or c_interface. 
* Create tickets for the specific improvements asked in the survey ("get rid of batches, batches is the biggest problem for end user", "Python 3", "C# interface;NuGet BigARTM", "better memory consumption", "You added a topic selection into BigARTM, but there is no easy way to cansel bad toopics from the model")

**Comment by sashafrey** [comment]
Thanks for everyone who participated in this survey!
