### ISSUE TITLE
Review python API and consider changes for v0.8.0

### ISSUE THREAD

**Issue by sashafrey** [bigartm/bigartm#489]
We need to review python API and consider making breaking changes for v0.8.0. From that point we  should not introduce any breaking changes for v0.8.X. Next change to break API is v0.9.0.

As a first input we can review this pull request to see if we need to grab anything from it:
https://github.com/bigartm/bigartm/pull/312/

**Comment by sashafrey** [comment]
Dictionaries
==========
The API for dictionaries is very cumbersome. Why are the part of the ARTM class? Why users need to give a "name" to their dictionaries? Why dictionary has a default name "dictionary.dict"? I don't think we have good answers to this... Here is an  alternative:

1. Move all operations on dictionaries into a separate class
   ```
   ARTM.create_dictionary -> Dictionary.create,
   ARTM.filter_dictionary -> Dictionary.filter,
   ARTM.gather_dictionary -> Dictionary.gather,
   ARTM.load_dictinoary - >Dictionary.load,
   etc
   ```
2. Stop asking user to generate a "name" for the dictionary. We can do it automatically in python interface. Either GUID, or based on the file name of the dictionary file, provided by the user.
Since each Dictionary object has its own name the Dictionary.filter operation should either create a new Dictionary, or do this inplace. To me inplace is a better option.
3. Never specify `dictionary.dict` as a default name. There is no good default for a file name.
4. Remove `dictionary` argument from `fit_offline` and `fit_online` calls. Add `dictionary` argument to ARTM constructor . If user wants to initialize the model automatically (without calling `.initialize()` method) it should happen from the constructor. 
5. The `dictionary` argument in ARTM constructor can refer to either filename, or to Dictionary object. Same applies to `dictionary` argument in `.initialize()` method.
6. For a more complex scenario where dictionary is used more that to initialize the model user has to create Dictionary object.

If this API looks clean we can think how to implement it. The problem is that ARTM and Dictionary objects will refer to different `master_id`, and it implies that ARTM.py won't be able to access the dictionary --- currently each `master_id`  has its own namespace for dictionary names. But I'm sure I can fix this. The API should be as clear as possible, and the implementation must follow.

**Comment by sashafrey** [comment]
Defaults
=======
* why model by default has 10 topics? I suggest to remove the default and make this a required parameter.
* why fit_offline does 20 iterations? I suggest to either default to `1`, or to make this required.
* `num_processors = 0`; -- normally we use "None" to indicate "default".setting.

Other misc comments:
* `async` parameter in fit_offline --- I would remove this parameter for now, because in async mode we don't support score tracker. Or we need to clearly state this in the documentation.
* fit_online -- I suggest to split into two APIs; one having tau0, kappa, update_Every; other having apply_weight, decay_weight and update_After
* fit_transform --- just remove this
* `seed` in `initialize()` - would it makes sense to also add `seed` argument into ARTM constructor? (given that we move automatic initialization into constructor)
* save/load doesn't save/restore dictionaries, scores, regularizer, theta cache, score tracker info, etc. We need to reflect this in the documentation...

**Comment by Angriff** [comment]
Is it possible to provide simple access to values of p(t|w,d)? It is very good and useful feature for analysis of internal structure of documents (in JGibbsLDA library user can print the number of most probable topic and its probability)
Actually, I don't know is it appropriate to operate with 3-dimentional arrays... But, for instance, the way to do that is to make function `ARTM.detailed_decomposition(batch_vectorizer=None, theta_matrix_type='dense_theta', predict_class_id=None)`

**Comment by sashafrey** [comment]
@Angriff `p(t|w,d)` are already available via `ARTM.transform(batch_vectorizer, theta_matrix_type='dense_ptdw')`. You get back a flat theta matrix (no 3D) where each item has multiple columns - as many as the number of tokens in that document. These columns will have the same `item_id`. The order of columns with equal `item_id` is the same as the order of tokens in the input data (`batch.item.token_id`).

To save memory there is also 'sparse_ptdw'  which retrieves only the `p(t|w,d')` elements above certain threshold. It seems that python API doesn't let you configure that threshold, so it will retrieve all non-zero entries. The call with `sparse_ptdw` option should return a protobuf message `ThetaMatrix` containing `topic_index` field, described here:
http://docs.bigartm.org/en/stable/ref/messages.html#ThetaMatrix.topic_index

@AnyaP  used this API in the past and can help -- let her know if you find any issues. To play with this API it is probably a good idea to pass in a batch_vectorizer that only contains one document.

**Comment by sashafrey** [comment]
As for the API, we should consider adding a separate operation for `p(t|w, d)` extraction, like the suggested (`ARTM.detailed_decomposition`). Same for `predict_class_id`.

**Comment by sashafrey** [comment]
@Angriff Sorry for confusion -- I've added tons of details about sparse format in my answer, but in fact sparse theta matrix is not supported by python API.

**Comment by AnyaP** [comment]
Hi Everyone :)

In some scenarios we need only to compute some scores (e.g. perplexity) on a huuuuge hold-out data by transform()+get_score(). However, transform() necessarily saves Theta matrix which can be too large and leads to a dead kernel. Moreover, this transform()+get_score() actions can be unintuitive to a user, how just wants hold-out perplexity and has no idea about our caches for scores and their current state. 

Probably we should add an opportunity to feed hold-out-batches to get_score() to get the score on them (instead of training set). It could be analogous to the opportunity to feed hold-out-batches to fit_online/offline in case we want to track hold-out scores instead of those for training set.

Technically, for get_score(data) we would need to invoke transform() with request_type=None in TransformMasterModelArgs message. Could it be possible?

**Comment by sashafrey** [comment]
@AnyaP Yes, this sounds reasonable (and possible :)). To clarify, how get_score(data) should behave for phi-scores (those that only depend on phi matrix itself, not on the data)? Should we just ignore the data, or throw an exception to warn the user that it is not needed?

Also, note that for theta scores `get_score(data=None)` will return score from the cache, while `get_score(data=batch_vectorizer)` will calculate the score. Could this be confusing? It sound like we need a separate method `calc_score` where `data` argument is required.

**Comment by sashafrey** [comment]
This is fixed by recent pull requests.
See http://docs.bigartm.org/en/master/release_notes/python.html for all changes that had been made.
