### ISSUE TITLE
Include model.py in the online documentation

### ISSUE THREAD

**Issue by sashafrey** [bigartm/bigartm#490]
At the moment our online documentation has all but the most important class -- `model.py`. Let's include it!

http://bigartm.readthedocs.org/en/master/index.html
![image](https://cloud.githubusercontent.com/assets/1252606/13832073/c2cd0e1a-ebd8-11e5-9022-402f98edab60.png)

**Comment by sashafrey** [comment]
@AnyaP 
>И вытащить на сайт в читабельный вид ВСЕ функции из ARTM-model со всеми их параметрами и док-строками, которые прописывает Мурат. Тоже при необходимости причесав и дополнив небольшим на абзац текстом, что вообще-то у нас есть офлайновое обучение, онлайновое, можно считать метрики и добавлять регуляризаторы.

**Comment by JeanPaulShapo** [comment]
@MelLain I'd like to prevent you from refactoring docstrings, because you can simply include `sphinx.ext.napoleon` to enable docstrings in Google style (the style you used before).
Link <http://www.sphinx-doc.org/en/stable/ext/napoleon.html#module-sphinx.ext.napoleon>.
Sorry for late answer :(

**Comment by JeanPaulShapo** [comment]
Fixed by #494

**Comment by sashafrey** [comment]
@MelLain @JeanPaulShapo I think some recent commit broke the auto-generated documentation.. It no longer shows up here: http://docs.bigartm.org/en/master/python_interface/model.html

The build at readthedocs looks like this:
https://readthedocs.org/projects/bigartm/builds/3859634/
```
/home/docs/checkouts/readthedocs.org/user_builds/bigartm/checkouts/master/docs/python_interface/batches_utils.txt:6: WARNING: autodoc: failed to import module u'artm'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/bigartm/envs/master/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/bigartm/checkouts/master/python/artm/__init__.py", line 1, in <module>
    from model import ARTM
  File "/home/docs/checkouts/readthedocs.org/user_builds/bigartm/checkouts/master/python/artm/model.py", line 11, in <module>
    from . import wrapper
  File "/home/docs/checkouts/readthedocs.org/user_builds/bigartm/checkouts/master/python/artm/wrapper/__init__.py", line 3, in <module>
    from . import messages_pb2 as messages
ImportError: cannot import name messages_pb2
```

**Comment by sashafrey** [comment]
I think this is because we removed ``messages_pb2.py``.

**Comment by JeanPaulShapo** [comment]
@sashafrey If something don't work properly - let me know. Right now I see all documentation for 'master' branch :)
