### ISSUE TITLE
Implement classification for topics with several classes

### ISSUE THREAD

**Issue by bigartm** [bigartm/bigartm#50]
Classification refers to this:

![image](https://cloud.githubusercontent.com/assets/8783740/5221569/20479276-767e-11e4-98ed-30dca3a5630c.png)

Note that there is terminology issue in BigARTM. In BigARTM terms, the classification formula on the figure above assigns weights p(w|d) to different tokens w of a specific class_id.

**Comment by sashafrey** [comment]
Implemented in https://github.com/bigartm/bigartm/pull/336
