### ISSUE TITLE
Fit and Transform should return an error code if there is no data to process

### ISSUE THREAD

**Issue by sashafrey** [bigartm/bigartm#500]
FitOffline, FitOnline and Transfrom operations should report an error if user
- provides 0 batches, or 
- batches all together have 0 items, or
- items all have 0 tokens, or
- none of the tokens belongs to target modality.
  This help user to identify his error.

Note that this applies only to the the APIs listed above. ProcessBatches shouldn't make this check, at least for now.

The feature should be implemented in the core (e.g. it is NOT sufficient to do it in Python API only).

**Comment by AnyaP** [comment]
Absolutely agree!

**Comment by ofrei** [comment]
The fix is in progress... It will throw an error, plus add lines like this into the log:
```
I1106 23:31:15.116575 60888 master_component.cc:664] FitOffline: ItemsProcessed, num_items=100, num_batches=1, token_weight=9636, token_weight_in_effect=0
E1106 23:31:15.116575 60888 c_interface.cc:58] InvalidOperation :  FitOffline: no tokens in effect --- either tokens not present in the model, or tokens were ignored due to class_id
```

**Comment by ofrei** [comment]
@AnyaP Fixed! (next in my queue is the ticket about progress status in python)
