### ISSUE TITLE
Debug releases for windows have wrong VS redistributable

### ISSUE THREAD

**Issue by sashafrey** [bigartm/bigartm#516]
The VS redistributable binaries included in packages of debug flover have release version. For instance, we put `msvcp110.dll` instead of `msvcp110D.dll`. This is not a big deal because end users should not use debug versions -- they are only for developers, how are supposed to have visual studio installed on their machine anyway.

**Comment by ofrei** [comment]
Close, as we don't ship debug releases for Windows
