### ISSUE TITLE
master build fails outside of bigartm/build

### ISSUE THREAD

**Issue by omtcyf0** [bigartm/bigartm#523]
While trying to build BigARTM outside of `bigartm/build` (i.e. somewhere like `bigartm/../build`) I got the following error:

```
Generating ./artm/wrapper/messages_pb2.py...
Traceback (most recent call last):
  File "/home/omtcyf0/Documents/dev/src/bigartm/python/setup.py", line 83, in <module>
    cmdclass = {'build': build},
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/omtcyf0/Documents/dev/src/bigartm/python/setup.py", line 69, in run
    "./artm/wrapper/messages_pb2.py")
  File "/home/omtcyf0/Documents/dev/src/bigartm/python/setup.py", line 51, in generate_proto_files
    if subprocess.call(protoc_command):
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
AttributeError: 'NoneType' object has no attribute 'rfind'
```

Ubuntu 15.10, Python 2.7.10

**Comment by sashafrey** [comment]
@JeanPaulShapo Any ideas why what goes wrong with the script that generates python protobuf messages?

**Comment by JeanPaulShapo** [comment]
Seems it couldn't find any `protoc` executable.
@omtcyf0 
* do you have `protoc` executable in `build/3rdparty/protobuf-cmake/protoc` directory?
* could you collect output of `make`?

**Comment by omtcyf0** [comment]
@JeanPaulShapo 

Yes, there's no protoc exec.

Thus said,

* I don't
* sure thing. I'll put it below when I get home

Though build on stable completes w/o protoc executable. I'm not sure what changed, but in my humble opinion one of these choices would be totally reasonable.

* either create protoc exec in the build process
* or don't terminate the build w/o protoc exec like before

**Comment by JeanPaulShapo** [comment]
@omtcyf0 
* Commit which enabled auto-generating Python and C sources from Protobuf files (i.e messages.proto) is integrated only in `master` branch. That's why you don't have similar troubles on `stable`.
* I strongly believe we DO create protoc exec in the build process. If you don't have messages "Built target protoc" while building even on `stable`, it's really strange.

**Comment by omtcyf0** [comment]
@JeanPaulShapo 

Sorry for the inconvenience, there actually is protoc there.

Mysteriously, I don't get the mentioned error anymore... Though I didn't do anything ever since.

Thus said, I no longer have Python-related build issues.

However, I still struggle to build it using Clang.

Here's [the log](http://pastebin.com/jmQbSKQA). I'm not sure we want to discuss it here and maybe I should just close the issue since it's no longer reproducible, but anyway - that's the BigARTM <-> Clang issue I was talking about.

**Comment by JeanPaulShapo** [comment]
@omtcyf0 You can close this issue and open the one related to Clang, attaching the log. I'll investigate it.

**Comment by JeanPaulShapo** [comment]
@omtcyf0 
* you can build BigARTM with `clang` using -DBUILD_STATIC_BIGARTM=OFF (for my Fedora 22 it works perfectly)
* I think this comment will give you some useful information about Clang, GCC5 and Boost :smile: 
https://github.com/TrinityCore/TrinityCore/issues/15751#issuecomment-149807860

**Comment by omtcyf0** [comment]
@JeanPaulShapo 
Well, I couldn't reproduce build failure after some time, but I was wondering why ever since.

Here's what I discovered: the build fails and mentioned issue appears if `build` folder is not inside folder with `bigartm` source.

I.e. this works:

```
bigartm
--build
```

And this doesn't:

```
build
bigartm
```

This wasn't reflected in documentation to my knowledge and that seems weird after all.

**Comment by JeanPaulShapo** [comment]
@omtcyf0 If you directly follow instructions from [documentation](http://docs.bigartm.org/en/stable/installation/linux.html#download-sources-and-build), there'll be the former folder layout, because instructions suggest to create folder `build` into the folder with cloned repository (named `bigartm`).

In my opinion, the actual problem is that path to `protoc` executable is hard-coded in `setup.py` right now. Hope I'll fix it soon.

**Comment by omtcyf0** [comment]
@JeanPaulShapo 

Ah, okay.

Yes, exactly: this behaviour is still pretty weird and I was expecting the path to `protoc` being hardcoded somwhere, so you confirm my suspicions.

**Comment by JeanPaulShapo** [comment]
@omtcyf0 

PR #570 aimed to fix bug with hardcoded `protoc`, and I tested these changes on my machine. Could you check this PR and say is it ok now?

**Comment by omtcyf0** [comment]
@JeanPaulShapo 

Thank you very much for looking into this!

I checked it on my machine: fine aswell. Happy to see it upstream soon!
