### ISSUE TITLE
glog default must be configured to not buffer messages

### ISSUE THREAD

**Issue by sashafrey** [bigartm/bigartm#534]

**Comment by ofrei** [comment]
This is somewhat related to PR #695 (issue #113). 
Now the API to configure logging is documented [here](http://docs.bigartm.org/en/master/ref/c_interface.html#artmconfigurelogging).
>We recommend to set ``logbuflevel = -1`` to not buffer log messages. However by default BigARTM does not set this parameter, using the same default as provided by glog.
