### ISSUE TITLE
OSError: dlopen(~/bigartm/build/src/artm/libartm.dylib , 6): image not found

### ISSUE THREAD

**Issue by ayva** [bigartm/bigartm#573]
Hello, 
I've installed BigArtm in accordance with guidelines. 
I'm using Mac Os X El Capitan 10.11.5, BigArtm 0.8, Python 2.7 with anaconda 2.5. 

_import artm_ - works
_artm.BatchVectorizer()_ - [throws an error  ](https://www.dropbox.com/s/cryln4rppjwqr3j/Screenshot%202016-05-23%2015.27.28.png?dl=0)

> OSError: dlopen(~/bigartm/build/src/artm/libartm.dylib , 6): image not found
> 
> Failed to load artm shared library. Try to add the location of `artm.dylib` file into your PATH system variable, or to set ARTM_SHARED_LIBRARY - a specific system variable which may point to `artm.dylib` file, including the full path.

I do have the file  libartm.dylib in the folder "~/bigartm/build/src/artm/libartm.dylib" 
I did point ARTM_SHARED_LIBRARY variable and added it to .bash_profile

_sudo make install_ - doesn't install artm.dylib into folder "/usr/local/lib/" as expected.

**Comment by sashafrey** [comment]
Hi,

1) Try to specify a full path to ``libartm.dylib``, and maybe put it directly in your python script:
```
os.environment["ARTM_SHARED_LIBRARY"] = r'/users/username/bigartm/build/src/artm/libartm.dylib'
```

2) It maybe specific to Os X El Capitan: http://stackoverflow.com/questions/32905322/oserror-dlopenlibsystem-dylib-6-image-not-found . 
>I suspect (but can't confirm) the System Integrity Protection (SIP) of OSX El Capitan is preventing access to your /usr/lib folder.

3) Do you have 64 bit anaconda + 64 bit BigARTM? A mismatch between 32 bit and 64 big may cause `dlopen` issues.

**Comment by ayva** [comment]
Fixed. Thanks for the help. I added this code to ipython notebook to explicitly rewrite the variable.

```
import os
os.environ['ARTM_SHARED_LIBRARY']='/users/username/bigartm/build/src/artm/libartm.dylib'
```

**Comment by JeanPaulShapo** [comment]
@sashafrey Seems this error is only about absolute path importing: [one of the answers to mentiond question](https://stackoverflow.com/a/32915082/3152876). Maybe it's useful to include note about absolute paths in documentation?
