### ISSUE TITLE
v 8.0 build failed on Mac OS

### ISSUE THREAD

**Issue by MelLain** [bigartm/bigartm#594]
Attempt to build version 8.0 of the  library on Mac OS fails with following output:

clang: warning: argument unused during compilation: '-pthread'
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/bigartm/bigartm] Error 1
make[1]: *** [src/bigartm/CMakeFiles/bigartm.dir/all] Error 2
make: *** [all] Error 2

**Comment by sashafrey** [comment]
Most build issues in ``bigartm`` (CLI) I've seen so far were solved by turning off static linkage (``cmake -DBUILD_STATIC_BIGARTM=OFF ..``). Have you tried this?

**Comment by MelLain** [comment]
It seems, that this fix has helped, thanks!

**Comment by JeanPaulShapo** [comment]
@MelLain Can you reproduce this bug in the clean build directory, doing the same steps?
