### ISSUE TITLE
Add verbose parameter in fit_offline and fit_online to show info about model fitting process

### ISSUE THREAD

**Issue by nadiinchi** [bigartm/bigartm#602]
When running on big collections user doesn't know how long the model will fit. In sklearn classes usually have integer 'verbose' parameter that controls the verbosity of model learning process. In BigARTM we can print how many iterations of EM-algorithm have been done already.

**Comment by nadiinchi** [comment]
@sashafrey I cannot assign label 'enhancement', please assign

**Comment by JeanPaulShapo** [comment]
@nadiinchi #447?
