### ISSUE TITLE
bigartm CLI fails without --threads param

### ISSUE THREAD

**Issue by ofrei** [bigartm/bigartm#634]
I'm getting the following error on lastest master branch:
```
>bigartm.exe -d d:\Datasets\docword.kos.txt -v d:\Datasets\vocab.kos.txt -p 10
Parsing text collection... OK.
Gathering dictionary from batches... OK.
Initializing random model from dictionary... OK.
Number of tokens in the model: 6906
================= Processing started.
Exception  : InvalidOperation :  Can't process batches because there are no processors. Check your MasterModelConfig.num_processors setting.
```
I'm fairly sure this has forked before, and by default bigartm CLI set threads to number of cores in the machine. I haven't checked if the same problem appears in stable branch.

**Comment by JeanPaulShapo** [comment]
@sashafrey I came across this issue on my machine too. However, setting default number to -1 solves the problem. Is it ok to simply change default number of threads from 0 to -1 in bigartm CLI code?
