### ISSUE TITLE
Indicate progress during dataset parsing

### ISSUE THREAD

**Issue by vmarkovtsev** [bigartm/bigartm#636]
Currently, bigartm CLI just prints `Parsing text collection...`. It would be nice if it also printed percentage of the parsing done in case of an interactive terminal stdout. I have 20GB Vowpal Wabbit file and it itakes 30 mins. It would be super cool if it also printed ETA as well.

I will be glad to implement this feature if you agree.

**Comment by ofrei** [comment]
@vmarkovtsev Yes, this also a very good idea. I can also think about how do we speed up the parsing... This is the first time that I see people parsing large VW files. Another alternative is to generate several smaller VW files, and parse them from multiple bigartm CLI instances -- but this is of course more cumbersome.

**Comment by vmarkovtsev** [comment]
Great! BTW, I got really exciting results with bigartm on GitHub repo topic modelling. Besides, it consumed moderate amount of RAM, only 23GB. 👍 👍 👍

**Comment by ofrei** [comment]
@vmarkovtsev Sounds very interesting! 
For the RAM, there are plenty of opportunities to cut it down in our code. We still use dense matrix to represent phi matrix (e.g. word-topic matrix), but there are plans to fix this.
