### ISSUE TITLE
Review of the article

### ISSUE THREAD

**Issue by vmarkovtsev** [bigartm/bigartm#650]
Hi guys, could you please review the article I wrote about BigARTM before we spread the word around the world:

http://blog.sourced.tech/post/github_topic_modeling/

**Comment by ofrei** [comment]
This is very exiting, thank you this fantastic post! Everything looks great, except perhaps few minor things:

- I failed to access links to https://storage.googleapis.com ("OpenDocument spreadsheet with the extracted topics" and others) -- I got "The specified bucket does not exist"
- redundant `)` in ``regularization) is desirable for stating machine learning problems``
- this is up to you but maybe it would a good idea to add links to ARTM / BigARTM publications (for example the two most recent from https://github.com/bigartm/bigartm#references)

>I hope the project will improve the documentation and add examples about them. 
Yes, we will. Thank you, this is a very valid feedback! 

Btw, would you be interested in building a hierarchical topic models? For example two or three layers (let's say T1=10, T2=100, T3=1000 topics), each topic having a few parental topics in the previous layers? We've recently implemented this feature in Python API, but haven't fully tested it yet. This may speedup manual labeling process, thus allowing for a larger number of topics in your experiment.

**Comment by vmarkovtsev** [comment]
Thank you very much! I fixed all the three points.

Yep, hierarchical topic models look really useful for us! I don't remember why exactly, but I had to abandon Python API and use CLI instead. Does CLI support this feature?

**Comment by ofrei** [comment]
@vmarkovtsev For now hierarchies are only available in Python, but I agree it would be really nice to also implement them in CLI. Could you help design the API for this feature in BigARTM CLI (e.g. suggest which switches we need, ans also what output formats would you expect for hierarchical model)? It would be really great, as I generally don't know what exactly people expect when they say "hierarchy" :)

**Comment by ofrei** [comment]
@vmarkovtsev I've opened issue #651  to track this, please comment there if you have any input. As I said, any input is very valuable!

**Comment by vmarkovtsev** [comment]
Follow up: [habrahabr](https://habrahabr.ru/post/312596/).
