### ISSUE TITLE
Top tokens of a small topic

### ISSUE THREAD

**Issue by MasYes** [bigartm/bigartm#656]
If there are no terms with positive probability in a topic, then this line is shown as the top tokens of the topic
：( 0) －( 0) ，( 0) ）( 0) （( 0) ﬁnite( 0) ﬁeld( 0) 한( 0) 영( 0) 사( 0)

**Comment by ofrei** [comment]
@MasYes I've tried but didn't reproduce the issue. Could you add more details about reprosteps? Do you use BigARTM Command line interface? From which operating system?

On my Windows machine it looks as follows, using NIPS collection from [here](docs.bigartm.org/en/master/download.html).
```
>bigartm.exe -p 3 -d c:\datasets\docword.nips.txt -v c:\datasets\vocab.nips.txt -t 2 --regularizer "500000 sparsePhi"  --final-score TopTokens
Parsing text collection... OK.
3 batches created with total of 1500 items, and 12419 words in the dictionary; NNZ = 746316, average token weight is 2.5892
Gathering dictionary from batches... OK.  Dictionary size: 12419
Initializing random model from dictionary... OK.
Number of tokens in the model: 12419
================= Processing started.
================= Iteration 1 took 00:00:00.319
================= Iteration 2 took 00:00:00.334
================= Iteration 3 took 00:00:00.316
TopTokens (TopTokens):
#1: zwislocki( 0) zurich( 0) zur( 0) zue( 0) zucker( 0) zoubin( 0) zornetzer( 0) zorn( 0) zoo( 0) zones( 0)
#2: zwislocki( 0) zurich( 0) zur( 0) zue( 0) zucker( 0) zoubin( 0) zornetzer( 0) zorn( 0) zoo( 0) zones( 0)
```

**Comment by MasYes** [comment]
Yeah, I have the same result. Sorry, I think it's my fault: maybe these symbols were in my vocabulary but I used wrong way to check it. If I will be able to reproduce it on a collection without these symbols then I'll send my collection. Sorry :(

**Comment by ofrei** [comment]
The closing this ticket for now -- feel free to reopen if it reproduces.
