### ISSUE TITLE
installation/linux.txt - macos instructions

### ISSUE THREAD

**Issue by demidovakatya** [bigartm/bigartm#662]
> shared library `libartm.so` (**`artm.dylib`** for Max OS-X) into folder `/usr/local/lib/`;
([source](http://docs.bigartm.org/en/stable/installation/linux.html#system-wide-installation))

After following the instructions, I've got `/usr/local/lib/libartm.dylib`. This name is used when we set the `ARTM_SHARED_LIBRARY` variable ([here](http://docs.bigartm.org/en/stable/installation/linux.html#configure-bigartm-python-api)) as well.

> On Mac OS distributions: `sudo brew install git cmake boost`

It is not recommended to use `sudo` with `brew`. When I follow the instruction, I get _Error: Cowardly refusing to 'sudo brew install'_ (read more about this feature [here](https://github.com/Homebrew/brew/blob/master/docs/FAQ.md#why-does-homebrew-say-sudo-is-bad-).

Nevertheless, I guess, these are just small typos.

**Comment by demidovakatya** [comment]
more info on `sudo brew`:
> If we have not merged a pull request to add privilege dropping by November 1st
2016 running Homebrew as root will be disabled. No Homebrew maintainers plan
to work on this functionality.

**Comment by ofrei** [comment]
@demidovakatya thanks for pointing out to this. Do you have an alternative way of installing git, cmake and boost libraries on MAC ? There must be some other "recommended" way that avoids `sudo brew install`.

**Comment by demidovakatya** [comment]
I've installed these libraries using just `brew`, and there haven't been any problems so far. Is sudo really required?

**Comment by ofrei** [comment]
@demidovakatya probably not, I'll remove it from the installation instructions. Thanks!
