### ISSUE TITLE
Segfault while getting readable model with big data

### ISSUE THREAD

**Issue by dimack** [bigartm/bigartm#679]
My model is about 2M documents with 1,5M dictionary and 400 topics.
I'm getting segmentation fault when trying to save model in readable format.

Actualy, integer overflow happens and memcpy trying to allocate memory of negative size ([it happens here](https://github.com/bigartm/bigartm/blob/master/src/artm/c_interface.cc#L192l))
I'm running bigartm in linux(x64) console, where **int size is 4 bytes**(and size_t is 8 bytes).

Why all C interface uses **int** instead of more suitable **size_t** in most cases?

My model is big, cause i don't know language in general, and so i can't use stemming or things like this.
And my dictionary must be quite big to allocate all word variations.

**Comment by ofrei** [comment]
@dimack Thanks for reporting this. The original reason to use `int` in c_interface was because all methods were copying protobuf messages, which have a hard limit of 2 GB. This is still the case with latest protobuf 3.0.0, and the recommendation from google is not to transfer large messages, but rather split into smaller messages. BigARTM tries to follow this, but there is still a room for improvement (as you see).

Now there are some methods that work with non-protobuf buffers (for example `ArtmCopyRequestedObject`). In this case it makes sense to use `size_t`.

As a workaround, could you retrieve the model topic by topic? E.g. 
* use `topic_names` if use use `ARTM.get_phi(topic_names)` from python; 
* use `GetTopicModelArgs.topic_name` if you use `MasterModel.GetTopicModel(GetTopicModelArgs)` if you use C++

**Comment by ofrei** [comment]
@dimack The issue should be fixed. I've reproduced the crash with bigartm commandline tool as you described, and after this change the crash no longer happens.
But are you OK with getting large text file? I'm thinking of an option to export topic model in sparse text format, like one `(token, class_id, topic_name, value)` tuple per line. Ideally it should be a compressed `gz` format. Please let me know if there is an alternative solution that will suite you better.

**Comment by dimack** [comment]
Thanks! Bug is fixed :)
I'm not reading text file, I load binary file through bigartm c++ interface, then import it to my project.

Actually, there is some problem with memory usage of bigartm model. I use different representation of model and here are some statistics:

**My project**
Vocabulary imported...332.1Mb 2774269 terms
model imported...80.82Mb 1242 topics

**BigArtm**
Vocabulary imported... 1.083Gb 1406804 terms
model imported... 11.7Gb 400 topics

As you can see, i use bigger vocabulary and more topics but much less memory.
My model is quite simple:
Vocabulary keep terms and theirs ids, also tf and df. Vocabulary has two indexes by id and by term (for quiсk search)
Model is vector of topics and topics is sorted vector of topic terms. Topic term is a structure of vocabulary term id and weight of term in topic.

This representation is sufficient for bayes classification, for example.
The trick is that topic terms don't keep terms itself but refers to vocabulary by id.

Perhaps it would be useful for you.

**Comment by ofrei** [comment]
@dimack Yes, this is useful but somewhat embarrassing -- BigARTM must be better at memory usage..
In your case would it be correct to say that each topic has on average ~8530 terms? (80.82MB / 8 bytes / 1242)?
Do you use BigARTM v0.8.2? From this version matrices are automatically save some memory if they are sparse enough. Could you please add `--score PeakMemory Perplexity SparsityPhi SparsityTheta` to you BigARTM command and paste here the result?

**Comment by dimack** [comment]
Actually, topic has on average ~5500 terms (80.82MB / 12 bytes / 1242). Yes, it's close to truth.

I fetched last master and rebuild project. Here some results:

bigartm \\
    --score PeakMemory Perplexity SparsityPhi \\
    --use-batches some_batches \\
    --use-dictionary some.dict \\
    --num-collection-passes 5 \\
    --batch-size 10000 \\
    --update-every 1000 \\
    --tau0 128 \\
    --kappa 0.5 \\
    --threads 16 \\
    --topics 400 \\
    --regularizer "1000 decorrelation" \\
    --regularizer "0.1 sparsePhi" "0.1 sparseTheta" \\
    --save-model some.model

Using 4867 batches from 'some_batches'
Loading dictionary file from some.dict... OK.  Dictionary size: 1616791
Initializing random model from dictionary... OK.  
Number of tokens in the model: 1616791
================= Scores before processing.
PeakMemory      = <1 MB
	Model nwt: 2894 MB, |T|=400, |W| = 1616791;
	Model pwt: 2894 MB, |T|=400, |W| = 1616791;
	Dictionary main_dictionary: 237 MB, |W|=1616791;
	Cache size: <1 MB in total across 0 entries;
Perplexity      = 0
SparsityPhi     = 0
================= Processing started.
PeakMemory      = <1 MB
	Model nwt: 2838 MB, |T|=400, |W| = 1616791;
	Model pwt: 460 MB, |T|=400, |W| = 1616791;
	Model rwt: 2897 MB, |T|=400, |W| = 1616791;
	Dictionary main_dictionary: 237 MB, |W|=1616791;
	Cache size: <1 MB in total across 0 entries;
Perplexity      = 7667.82
SparsityPhi     = 0.994934
================= Iteration 1 took 00:21:29.978
PeakMemory      = <1 MB
	Model nwt: 2838 MB, |T|=400, |W| = 1616791;
	Model pwt: 458 MB, |T|=400, |W| = 1616791;
	Model rwt: 2897 MB, |T|=400, |W| = 1616791;
	Dictionary main_dictionary: 237 MB, |W|=1616791;
	Cache size: <1 MB in total across 0 entries;
Perplexity      = 1986.06
SparsityPhi     = 0.995331
================= Iteration 2 took 00:21:42.282
PeakMemory      = <1 MB
	Model nwt: 2838 MB, |T|=400, |W| = 1616791;
	Model pwt: 457 MB, |T|=400, |W| = 1616791;
	Model rwt: 2897 MB, |T|=400, |W| = 1616791;
	Dictionary main_dictionary: 237 MB, |W|=1616791;
	Cache size: <1 MB in total across 0 entries;
Perplexity      = 1750.11
SparsityPhi     = 0.995676
================= Iteration 3 took 00:21:09.296
PeakMemory      = <1 MB
	Model nwt: 2838 MB, |T|=400, |W| = 1616791;
	Model pwt: 456 MB, |T|=400, |W| = 1616791;
	Model rwt: 2897 MB, |T|=400, |W| = 1616791;
	Dictionary main_dictionary: 237 MB, |W|=1616791;
	Cache size: <1 MB in total across 0 entries;
Perplexity      = 1629.85
SparsityPhi     = 0.995993
================= Iteration 4 took 00:21:15.939
PeakMemory      = <1 MB
	Model nwt: 2838 MB, |T|=400, |W| = 1616791;
	Model pwt: 455 MB, |T|=400, |W| = 1616791;
	Model rwt: 2897 MB, |T|=400, |W| = 1616791;
	Dictionary main_dictionary: 237 MB, |W|=1616791;
	Cache size: <1 MB in total across 0 entries;
Perplexity      = 1552.5
SparsityPhi     = 0.996286
================= Iteration 5 took 00:21:19.237


What pwt, nwt and rwt means? Is pwt - phi matrix? 
And can you tell me where to find EM-like algorithm source code in bigartm(file, line) ?

**Comment by ofrei** [comment]
>What pwt, nwt and rwt means? Is pwt - phi matrix?
>And can you tell me where to find EM-like algorithm source code in bigartm(file, line) ?

Yes, `pwt` refers to the phi matrix. Notation for `pwt` and `nwt` follows [this](https://s3-eu-west-1.amazonaws.com/artm/Voron15cikm-tm.pdf) paper -- see formulas (2), (3). In the code they are (potentially sparse) matrices of size |W| * |T|. Matrix `pwt` is normalized so that for each topic `t` we have `sum_w p_wt = 1` . Both `nwt` and `rwt` are also matrices of size `|W| * |T|`. `nwt` is easier to see from formula (3) in the paper, `rwt` is the regularization part of formula (4). Without regularization `pwt = norm(nwt)`, with regularization `pwt = norm(nwt+rwt)`.

The offline version of EM-like algorithm is [here](https://github.com/bigartm/bigartm/blob/master/src/artm/core/master_component.cc#L1057) (file `master_component.cc` method `ExecuteOfflineAlgorithm`). Step `ProcessBatches` re-calculates `nwt` with given `pwt` matrix, steps `Regularize` and `Normalize` recalculate `pwt` from `nwt`.

**Comment by dimack** [comment]
Thanks!

**Comment by ofrei** [comment]
Also thank you for sharing the  log! Sparse storage of phi matrices is somewhat working, but not good enough. With 99.6% sparse matrix it is down to `455 MB` versus `2897 MB`. 
First, I need to make sure that other matrices (e.g. `nwt` and `rwt`) are also sparse. This is more of an algorithmic issue that we need to address with better math behind ARTM.
Then on technical side there is a problem with dictionary being included in each model. I know that `237 MB` of dictionary is also part of `nwt`, `pwt` and `rwt`. Fixing this should reduce `pwt` down to `455 - 237  = 218 MB` (which can be further improved with even more efficient sparse storage; the current one -- (PackedValues)[https://github.com/bigartm/bigartm/blob/master/src/artm/core/dense_phi_matrix.h#L101], stores some redundant stuff).
