### ISSUE TITLE
Fix Make install for Linux

### ISSUE THREAD

**Issue by bigartm** [bigartm/bigartm#70]
Currently `CMakeLists.txt` files are not configured to produce meanunful `make install` scripts for Linux. This should be fixed. If I understand correctly, `make install` should put all relevant BigARTM binaries and shared libraries into `/usr/local/lib` and `/usr/local/bin` folders. However I'm not an expert on Linux. If you have any suggestions on the behavior of `make install` - please share your thoughts...

**Comment by sashafrey** [comment]
@JeanPaulShapo Do you have any thoughts on `make install` for BigARTM? Could you try it out, and suggest a behavior that Linux users would normally expect? Is it important to fix, or this is something people normally shouldn't care about?

**Comment by JeanPaulShapo** [comment]
@sashafrey Ok, I'll try it out. Altough I'm not experienced with normal behaviour of `make install`
(I usually use package managers), seems it's not really hard to figure it out. And, of course, this command is important. For example, we can find it while installing Python interpreter from sources.

**Comment by sashafrey** [comment]
Fixed by #378
