### ISSUE TITLE
Installing BigARTM for Ubuntu 16 using python 2

### ISSUE THREAD

**Issue by Seriont** [bigartm/bigartm#728]
I followed all the instructions from http://docs.bigartm.org/en/stable/installation/linux.html
I'm using Ubuntu 16.04 and made the installation for python2. When I tried to run my program in ipython notebook, I got an error:
/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm_notebook.pyc in status_printer(_, total, desc)     102             pbar.description = desc     103         # Prepare status text --> 104         ptext = HTML()     105         # Only way to place text to the right of the bar is to use a container     106         container = HBox(children=[pbar, ptext])  NameError: global name 'HTML' is not defined
Rebuilding the project for python3 solved this problem.

**Comment by bt2901** [comment]
We probably will be dropping python 2 support, so I'm closing this.
