### ISSUE TITLE
Tutorial for linux users

### ISSUE THREAD

**Issue by bigartm** [bigartm/bigartm#74]
Currently there is no tutorial for linux users.  The following commands are essential but can be found only in travis-ci script:

  - cp build/3rdparty/protobuf-cmake/protoc/protoc 3rdparty/protobuf/src/
  - cd 3rdparty/protobuf/python && python setup.py build && sudo python setup.py install && cd ../../..
  - export PYTHONPATH=`pwd`/src/python:$PYTHONPATH
  - export ARTM_SHARED_LIBRARY=`pwd`/build/src/artm/libartm.so

The option without 'sudo python setup.py install' also should be documented.

**Comment by sashafrey** [comment]
Tutorial is available: http://docs.bigartm.org/en/latest/tutorials/linux_basic.html
