### ISSUE TITLE
Measure GetThetaMatrix() time for classification of one document

### ISSUE THREAD

**Issue by bigartm** [bigartm/bigartm#75]
Performance of GetThetaMatrix() for a new document is especially important because this operation can be used in production to serve user queries. Let's measure current performance and improve it if needed.

**Comment by sashafrey** [comment]
According to the data published in ``Non-Bayesian Additive Regularization for
Multimodal Topic Modeling of Large Collections`` the throughput is 1400 docs per second (document size was quite short - about 100 words). The latency hasn't been measures but it must be below `0.1 sec`.
