### ISSUE TITLE
[Feature request] please make your project citeable

### ISSUE THREAD

**Issue by vmarkovtsev** [bigartm/bigartm#755]
As stated in https://guides.github.com/activities/citable-code/ there is a way to obtain DOI for your open source project on GitHub. Please do! I am citing BigARTM in my paper and would benefit much!

**Comment by ofrei** [comment]
@vmarkovtsev Thanks, great suggestion! I've put the DOI of the latest BigARTM release (v0.8.2) in the README.md

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.288960.svg)](https://doi.org/10.5281/zenodo.288960)
