### ISSUE TITLE
[Feature reuest] Get phi as matrix

### ISSUE THREAD

**Issue by fedimser** [bigartm/bigartm#758]
When there are the same words in different modalities, we can't definetly restore phi from dataframe, and people have to do hacky things like saving several phi's for each modality.

We need fucntion like get_phi() in interface, but which returns array-like object, in which rows are ordered in accordance to word order in dictionary file (so I will be able to restore it definetly).

P.S. I know about get_phi().values, but it, in general case, randomly shuffles rows.

**Comment by ofrei** [comment]
@fedimser You are right, thanks for reporting this. May I ask you to review or test #759 and let me know if it it looks right? The change adds api `ARTM.get_phi_dense` that should solve this issue.
