### ISSUE TITLE
Approximation of zero p(w|d) in perlexity calculation for collection with several modalities

### ISSUE THREAD

**Issue by Angriff** [bigartm/bigartm#803]
Formula for perplexity calculation:
![perplexity](https://cloud.githubusercontent.com/assets/6429935/26248485/4d52dafa-3cab-11e7-9d9b-ab0423a59fa1.png)
In BigARTM instead of zero *p(w|d)* (as far as I know) value *n_w/N* is used at this moment. Here *n_w* is frequency of word *w* in collection, *N* is length of collection in words by **all modalities**. It means that the value of model perplexity (calculated for one modality) depends on frequencies of words from another modalities. This is not good to my mind =)

Value *n_w/N* is stored in Dictionary's field *token_value*. I think it is possible to correct situation with replacing this value by *n_w/N*, but here *N* will be full length of collection by modality of word *w*.

**Comment by JeanPaulShapo** [comment]
Fixed in #814
