### ISSUE TITLE
Bug in the constructor of BatchVectorizer

### ISSUE THREAD

**Issue by OOliOO** [bigartm/bigartm#808]
It doesn't work when data_format='bow_n_wd'. The problem seems to be in _parse_n_wd().
Replacing the line
for token_id, value in enumerate(col):
with
for token_id, value in enumerate(col.T):
(line number ~217 in batches_utils.py) seems to fix the issue.

**Comment by MelLain** [comment]
Please compare your experiment code with n_wd section in this test

https://github.com/bigartm/bigartm/blob/master/python/tests/artm/test_batches_utils.py

and also with example in our README

**Comment by OOliOO** [comment]
Thank you for the reply. Apparently the problem was that I did not convert the n_wd matrix into a numpy array, but instead used the matrix directly.
