### ISSUE TITLE
Fix build errors on OS X

### ISSUE THREAD

**Issue by sashafrey** [bigartm/bigartm#81]
See error message below.
Use OS X environment on TravisCi to reproduce this issue.

5:~/workspace/bigartm/build$ make 
[  1%] Built target gflags-static
[  1%] Building CXX object 3rdparty/glog/CMakeFiles/google-glog.dir/src/symbolize.cc.o
/Users/romovpa/workspace/bigartm/3rdparty/glog/src/symbolize.cc:669:10: fatal error: 'config.h' file not found
#include "config.h"
         ^
1 error generated.
make[2]: *** [3rdparty/glog/CMakeFiles/google-glog.dir/src/symbolize.cc.o] Error 1
make[1]: *** [3rdparty/glog/CMakeFiles/google-glog.dir/all] Error 2
make: *** [all] Error 2

**Comment by bigartm** [comment]
Closing this ticket -  Mac OS X is now set as default build environment for travis (our CI system), and build is green. Please open a separate ticket if there are any remaining issues on your Mac OS X system.
