### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by electronick1** [bigartm/bigartm#815]
Got this error when run "make" on Mac:

[ 91%] Linking CXX shared library ../../lib/libartm.dylib
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
Undefined symbols for architecture x86_64:
  "google::FlagRegisterer::FlagRegisterer<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(char const*, char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)", referenced from:
      __GLOBAL__sub_I_logging.cc in libgoogle-glog.a(logging.cc.o)
      __GLOBAL__sub_I_vlog_is_on.cc in libgoogle-glog.a(vlog_is_on.cc.o)
  "google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)", referenced from:
      __GLOBAL__sub_I_logging.cc in libgoogle-glog.a(logging.cc.o)
      __GLOBAL__sub_I_utilities.cc in libgoogle-glog.a(utilities.cc.o)
  "google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)", referenced from:
      __GLOBAL__sub_I_logging.cc in libgoogle-glog.a(logging.cc.o)
      __GLOBAL__sub_I_vlog_is_on.cc in libgoogle-glog.a(vlog_is_on.cc.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libartm.dylib] Error 1
make[1]: *** [src/artm/CMakeFiles/artm.dir/all] Error 2
make: *** [all] Error 2

Can you please help me with advice

**Comment by electronick1** [comment]
More clear picture
<img width="1279" alt="screen shot 2017-06-20 at 5 01 05 pm" src="https://user-images.githubusercontent.com/5982083/27337224-7653f554-55da-11e7-905e-b8d97dacb1a1.png">

**Comment by JeanPaulShapo** [comment]
@electronick1 
* Could you list all commands you type when building BigARTM on Mac?
* Is it possible to show all log of all executed commands (not only the last part with error), e.g. as a text?
* Do you have system version of Google glog library? If so, try to uninstall it and build BigARTM from scratch again.

**Comment by electronick1** [comment]
Tried to uninstall it, this is second try:

Commands:
- brew upgrade git cmake boost
-git clone --branch=stable https://github.com/bigartm/bigartm.git
- cd bigartm
- mkdir build && cd build
-  cmake ..
- make


Log:
[  2%] Built target gflags-static
[  5%] Built target google-glog
[ 31%] Built target libprotobuf
[ 63%] Built target libprotoc
[ 64%] Built target protoc
[ 73%] Built target libprotobuf-lite
[ 73%] Built target proto_generation
[ 74%] Built target messages_proto
[ 75%] Built target internals_proto
[ 91%] Built target artm-static
[ 91%] Linking CXX shared library ../../lib/libartm.dylib
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
Undefined symbols for architecture x86_64:
  "google::FlagRegisterer::FlagRegisterer<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(char const*, char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)", referenced from:
      __GLOBAL__sub_I_logging.cc in libgoogle-glog.a(logging.cc.o)
      __GLOBAL__sub_I_vlog_is_on.cc in libgoogle-glog.a(vlog_is_on.cc.o)
  "google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)", referenced from:
      __GLOBAL__sub_I_logging.cc in libgoogle-glog.a(logging.cc.o)
      __GLOBAL__sub_I_utilities.cc in libgoogle-glog.a(utilities.cc.o)
  "google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)", referenced from:
      __GLOBAL__sub_I_logging.cc in libgoogle-glog.a(logging.cc.o)
      __GLOBAL__sub_I_vlog_is_on.cc in libgoogle-glog.a(vlog_is_on.cc.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libartm.dylib] Error 1
make[1]: *** [src/artm/CMakeFiles/artm.dir/all] Error 2
make: *** [all] Error 2


log for cmake:

-- Build type: Release
-- Boost version: 1.64.0
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   thread
--   program_options
--   date_time
--   filesystem
--   iostreams
--   system
--   chrono
--   timer
--   atomic
--   regex
-- Today is: Tue, 20 Jun 2017 19:27:26 +0300

-- forcing C++11 support on this platform
-- configuring for build type: Release
CMake Warning (dev) at 3rdparty/protobuf-3.0.0/cmake/install.cmake:41 (message):
  The file
  "/Users/oleg/programming/work_doist/play_with_BIGARTM/bigartm/3rdparty/protobuf-3.0.0/src/google/protobuf/repeated_field_reflection.h"
  is listed in
  "/Users/oleg/programming/work_doist/play_with_BIGARTM/bigartm/3rdparty/protobuf-3.0.0/cmake/cmake/extract_includes.bat.in"
  but there not exists.  The file will not be installed.
Call Stack (most recent call first):
  3rdparty/protobuf-3.0.0/cmake/CMakeLists.txt:159 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   thread
--   program_options
--   date_time
--   filesystem
--   iostreams
--   system
--   chrono
--   timer
--   atomic
--   regex
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/oleg/programming/work_doist/play_with_BIGARTM/bigartm/build

**Comment by JeanPaulShapo** [comment]
@electronick1 It seems that you haven't recreate `build` folder (i.e. `rm -rf build && mkdir build && cd build`) before rebuilding BigARTM, that's why we haven't got enough information about build process. Is it possible to do so?

**Comment by electronick1** [comment]
[log_make.txt](https://github.com/bigartm/bigartm/files/1089054/log_make.txt)
[log_cmake.txt](https://github.com/bigartm/bigartm/files/1089055/log_cmake.txt)

**Comment by JeanPaulShapo** [comment]
@electronick1 Seems that this problem relates to `gflags` library, because method, mentioned in error message, appear only in the code on this library.
Do you have system version of `gflags`? If yes, try to remove it if possible and rebuild BigARTM from scratch.

**Comment by electronick1** [comment]
@JeanPaulShapo sorry for long response.
Removing gflags from system helps, thank you very much for your help 👍

**Comment by JeanPaulShapo** [comment]
@electronick1 Great!
