### ISSUE TITLE
Can't import module python

### ISSUE THREAD

**Issue by LatatyeS** [bigartm/bigartm#848]
Hi! I've successfully installed bigartm on my Linux Mint 18.3, but it works from command line only.

When i try to import it in python, i have "ImportError: No module named artm" every time. 

I tried it for both pythons 2.7 and 3.6 and followed the instruction:
https://bigartm.readthedocs.io/en/stable/installation/linux.html

I saw a lot of similar problems in the internet, but no solution could help me.

So, i have no idea, how to solve this problem.
Could you help me with this issue, please?

**Comment by JeanPaulShapo** [comment]
Hi!
Seems there is not enough information to solve the issue. Please, try to answer the following questions:
* Do you have system-wide Python installation or maybe Anacoda/virtualenv?
* It seems that there are a lot of different scenarios on https://bigartm.readthedocs.io/en/stable/installation/linux.html. Could you specify exactly what commands with what arguments you've specified?
* Could you get logs of `cmake` and `make` commands (i.e. what is printed on standard output during building BigARTM) in textual form (i.e. something like `log.txt`)?

**Comment by LatatyeS** [comment]
Thanks for your answer!

- I use Anaconda

- My scenario for python 3.6:
 
 1) sudo apt-get install git build-essential libboost-all-dev
     sudo apt-get install cmake
 2) pip install -U numpy pandas protobuf==3.0.0 tqdm
 3) git clone --branch=stable https://github.com/bigartm/bigartm.git
     cd bigartm && mkdir build && cd build
     cmake -DPYTHON=python3 .. >> cmakeout.txt 2>&1
    make >> makeout.txt 2>&1
    sudo make install >> makeinstallout.txt 2>&1
 4) export ARTM_SHARED_LIBRARY=/usr/local/lib/libartm.so
   
After this instruction command "bigartm" works in command line, but "import artm" doesn't work in python. 

Attaching log files:
[cmakeout.txt](https://github.com/bigartm/bigartm/files/1424536/cmakeout.txt)
[makeinstallout.txt](https://github.com/bigartm/bigartm/files/1424537/makeinstallout.txt)
[makeout.txt](https://github.com/bigartm/bigartm/files/1424538/makeout.txt)

**Comment by JeanPaulShapo** [comment]
It seems that you install python package as a root user to some folder in `/usr/local/`, that's why python from Anaconda installation doesn't find it.
Try to run `python setup.py install` from directory `path/to/bigartm/python'  from your default user, not root.
I.e. run the following:
```
cd ~/bigartm/python/
# assuming that python3 corresponds to Anaconda installation:
python3 setup.py install
```

After running the commands mentioned above, please give us some feedback (i.e. does it solve problem or not, or even some comments).

**Comment by LatatyeS** [comment]
Well, after runnig this, i have the following output:

```
running install
running bdist_egg
running egg_info
writing bigartm.egg-info/PKG-INFO
error: [Errno 13] Permission denied: 'bigartm.egg-info/PKG-INFO'
```

**Comment by JeanPaulShapo** [comment]
Ahh, I see, the folder `bigartm.egg-info` was created by root during `sudo make install`, there also can be folders `build` and `dist`.
It's OK to remove these directories from `~/bigartm/python/` folder, therefore, run
```
sudo rm -rf bigartm.egg-info build dist
python3 setup.py install
```

**Comment by LatatyeS** [comment]
Yes, it works now!

Thanks a lot for your help!
