### ISSUE TITLE
Error during MAKE on Ubuntu 16

### ISSUE THREAD

**Issue by vladimircape** [bigartm/bigartm#855]
Try to make, MAKE command and get

> [ 93%] Building CXX object src/artm_tests/CMakeFiles/artm_tests.dir/master_model_test.cc.o
> In file included from /home/vshebuniayeu/bigARTM/bigartm/src/artm_tests/master_model_test.cc:7:0:
> /home/vshebuniayeu/bigARTM/bigartm/3rdparty/gtest/fused-src/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int]’:
> /home/vshebuniayeu/bigARTM/bigartm/3rdparty/gtest/fused-src/gtest/gtest.h:18898:30:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int; bool lhs_is_null_literal = false]’
> /home/vshebuniayeu/bigARTM/bigartm/src/artm_tests/master_model_test.cc:110:5:   required from here
> /home/vshebuniayeu/bigARTM/bigartm/3rdparty/gtest/fused-src/gtest/gtest.h:18861:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>    if (expected == actual) {
>                 ^
> [ 94%] Building CXX object src/artm_tests/CMakeFiles/artm_tests.dir/multiple_classes_test.cc.o
> [ 94%] Building CXX object src/artm_tests/CMakeFiles/artm_tests.dir/regularizers_test.cc.o
> [ 94%] Building CXX object src/artm_tests/CMakeFiles/artm_tests.dir/scores_test.cc.o
> /home/vshebuniayeu/bigARTM/bigartm/src/artm_tests/scores_test.cc: In member function ‘virtual void Scores_ScoreTrackerExportImport_Test::TestBody()’:
> /home/vshebuniayeu/bigARTM/bigartm/src/artm_tests/scores_test.cc:165:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>    for (size_t i = 0; i < nPasses; ++i) {
>                         ^
> /home/vshebuniayeu/bigARTM/bigartm/src/artm_tests/scores_test.cc:172:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>    for (size_t i = 0; i < nPasses; ++i) {
>                         ^
> [ 95%] Building CXX object src/artm_tests/CMakeFiles/artm_tests.dir/repeatable_result_test.cc.o
> In file included from /home/vshebuniayeu/bigARTM/bigartm/src/artm_tests/repeatable_result_test.cc:4:0:
> /home/vshebuniayeu/bigARTM/bigartm/3rdparty/gtest/fused-src/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int]’:
> /home/vshebuniayeu/bigARTM/bigartm/3rdparty/gtest/fused-src/gtest/gtest.h:18898:30:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int; bool lhs_is_null_literal = false]’
> /home/vshebuniayeu/bigARTM/bigartm/src/artm_tests/repeatable_result_test.cc:72:3:   required from here
> /home/vshebuniayeu/bigARTM/bigartm/3rdparty/gtest/fused-src/gtest/gtest.h:18861:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>    if (expected == actual) {
>                 ^
> [ 95%] Building CXX object src/artm_tests/CMakeFiles/artm_tests.dir/supcry_test.cc.o
> [ 95%] Building CXX object src/artm_tests/CMakeFiles/artm_tests.dir/template_manager_test.cc.o
> [ 96%] Building CXX object src/artm_tests/CMakeFiles/artm_tests.dir/test_mother.cc.o
> [ 96%] Building CXX object src/artm_tests/CMakeFiles/artm_tests.dir/thread_safe_holder_test.cc.o
> [ 97%] Building CXX object src/artm_tests/CMakeFiles/artm_tests.dir/topic_seg_test.cc.o
> [ 97%] Building CXX object src/artm_tests/CMakeFiles/artm_tests.dir/__/__/3rdparty/gtest/fused-src/gtest/gtest_main.cc.o
> [ 97%] Building CXX object src/artm_tests/CMakeFiles/artm_tests.dir/__/__/3rdparty/gtest/fused-src/gtest/gtest-all.cc.o
> [ 98%] Building CXX object src/artm_tests/CMakeFiles/artm_tests.dir/__/artm/cpp_interface.cc.o
> [ 98%] Linking CXX executable ../../bin/artm_tests
> CMakeFiles/artm_tests.dir/collection_parser_test.cc.o: In function `CollectionParser_MatrixMarket_Test::TestBody()':
> collection_parser_test.cc:(.text+0x760): undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)'
> CMakeFiles/artm_tests.dir/collection_parser_test.cc.o: In function `CollectionParser_VowpalWabbit_Test::TestBody()':
> collection_parser_test.cc:(.text+0xdea): undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)'
> CMakeFiles/artm_tests.dir/collection_parser_test.cc.o: In function `CollectionParser_UciBagOfWords_Test::TestBody()':
> collection_parser_test.cc:(.text+0x29c0): undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)'
> CMakeFiles/artm_tests.dir/collection_parser_test.cc.o: In function `CollectionParser_Multiclass_Test::TestBody()':
> collection_parser_test.cc:(.text+0x33d2): undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)'
> ../../lib/libartm-static.a(helpers.cc.o): In function `artm::core::Helpers::ListAllBatches(boost::filesystem::path const&)':
> helpers.cc:(.text+0x1124): undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)'
> collect2: error: ld returned 1 exit status
> src/artm_tests/CMakeFiles/artm_tests.dir/build.make:606: recipe for target 'bin/artm_tests' failed
> make[2]: *** [bin/artm_tests] Error 1
> CMakeFiles/Makefile2:661: recipe for target 'src/artm_tests/CMakeFiles/artm_tests.dir/all' failed
> make[1]: *** [src/artm_tests/CMakeFiles/artm_tests.dir/all] Error 2
> Makefile:138: recipe for target 'all' failed
> make: *** [all] Error 2
>

**Comment by JeanPaulShapo** [comment]
@vladimircape Could you provide full output of `cmake` and `make` commands you run?
Just do the following stuff on the fresh bigartm code:
```
your_cmake_command &> cmake_log.txt
your_make_command &> make_log.txt
```

**Comment by vladimircape** [comment]
`cmake -DPYTHON=python3 .. &> cmake_log.txt`

**cmake log**

> 
> -- The C compiler identification is GNU 4.9.4
> -- The CXX compiler identification is GNU 4.9.4
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Build type: Release
> -- Looking for include file unistd.h
> -- Looking for include file unistd.h - found
> -- Boost version: 1.58.0
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> -- Boost version: 1.58.0
> -- Found the following Boost libraries:
> --   thread
> --   program_options
> --   date_time
> --   filesystem
> --   iostreams
> --   system
> --   chrono
> --   timer
> --   atomic
> --   regex
> -- Looking for C++ include stdint.h
> -- Looking for C++ include stdint.h - found
> -- Looking for C++ include inttypes.h
> -- Looking for C++ include inttypes.h - found
> -- Looking for C++ include sys/types.h
> -- Looking for C++ include sys/types.h - found
> -- Looking for C++ include sys/stat.h
> -- Looking for C++ include sys/stat.h - found
> -- Looking for C++ include fnmatch.h
> -- Looking for C++ include fnmatch.h - found
> -- Looking for strtoll
> -- Looking for strtoll - found
> CMake Warning (dev) at 3rdparty/gflags/cmake/CheckCXXLibraryExists.cmake:43 (if):
>   Policy CMP0054 is not set: Only interpret if() arguments as variables or
>   keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
>   details.  Use the cmake_policy command to set the policy and suppress this
>   warning.
> 
>   Quoted variables like "CMAKE_HAVE_PTHREADS_CREATE" will no longer be
>   dereferenced when the policy is set to NEW.  Since the policy is not set
>   the OLD behavior will be used.
> Call Stack (most recent call first):
>   3rdparty/gflags/cmake/FindThreadsCXX.cmake:71 (CHECK_CXX_LIBRARY_EXISTS)
>   3rdparty/gflags/CMakeLists.txt:121 (find_package)
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Looking for C++ include stddef.h
> -- Looking for C++ include stddef.h - found
> -- Check size of pthread_rwlock_t
> -- Check size of pthread_rwlock_t - done
> -- running mz compiler detection tools
> -- GCC compatible compiler found
> -- compiler version 49
> -- C++11 support detected
> -- 64bit platform
> -- Today is: Аўт, 28 Ліс 2017 13:39:22 +0300
> 
> -- forcing C++11 support on this platform
> -- configuring for build type: Release
> -- Looking for include file dlfcn.h
> -- Looking for include file dlfcn.h - found
> -- Looking for include file execinfo.h
> -- Looking for include file execinfo.h - found
> -- Looking for include file glob.h
> -- Looking for include file glob.h - found
> -- Looking for include file pthread.h
> -- Looking for include file pthread.h - found
> -- Looking for include file gflags/gflags.h
> -- Looking for include file gflags/gflags.h - not found
> -- Looking for include file memory.h
> -- Looking for include file memory.h - found
> -- Looking for include file pthread.h
> -- Looking for include file pthread.h - found
> -- Looking for include file pwd.h
> -- Looking for include file pwd.h - found
> -- Looking for include file stdlib.h
> -- Looking for include file stdlib.h - found
> -- Looking for include file strings.h
> -- Looking for include file strings.h - found
> -- Looking for include file syscall.h
> -- Looking for include file syscall.h - found
> -- Looking for include file syslog.h
> -- Looking for include file syslog.h - found
> -- Looking for include file sys/call.h
> -- Looking for include file sys/call.h - not found
> -- Looking for include file sys/time.h
> -- Looking for include file sys/time.h - found
> -- Looking for include file sys/syscall.h
> -- Looking for include file sys/syscall.h - found
> -- Looking for include file sys/ucontext.h
> -- Looking for include file sys/ucontext.h - found
> -- Looking for include file sys/utsname.h
> -- Looking for include file sys/utsname.h - found
> -- Looking for include file ucontext.h
> -- Looking for include file ucontext.h - found
> -- Looking for include file unwind.h
> -- Looking for include file unwind.h - found
> -- Looking for fcntl
> -- Looking for fcntl - found
> -- Looking for sigaltstack
> -- Looking for sigaltstack - found
> -- Looking for __builtin_expect
> -- Looking for __builtin_expect - not found
> -- Looking for __sync_val_compare_and_swap
> -- Looking for __sync_val_compare_and_swap - not found
> CMake Warning (dev) at 3rdparty/protobuf-3.0.0/cmake/install.cmake:41 (message):
>   The file
>   "/home/user/bigARTM/bigartm/3rdparty/protobuf-3.0.0/src/google/protobuf/repeated_field_reflection.h"
>   is listed in
>   "/home/user/bigARTM/bigartm/3rdparty/protobuf-3.0.0/cmake/cmake/extract_includes.bat.in"
>   but there not exists.  The file will not be installed.
> Call Stack (most recent call first):
>   3rdparty/protobuf-3.0.0/cmake/CMakeLists.txt:159 (include)
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Performing Test COMPILER_SUPPORTS_CXX11
> -- Performing Test COMPILER_SUPPORTS_CXX11 - Success
> -- Performing Test COMPILER_SUPPORTS_CXX0X
> -- Performing Test COMPILER_SUPPORTS_CXX0X - Success
> -- Found GLOG: /home/user/bigARTM/bigartm/3rdparty/glog/src  
> -- Boost version: 1.58.0
> -- Found the following Boost libraries:
> --   thread
> --   program_options
> --   date_time
> --   filesystem
> --   iostreams
> --   system
> --   chrono
> --   timer
> --   atomic
> --   regex
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/user/bigARTM/bigartm/build
>

**Comment by vladimircape** [comment]
`make &> make_log.txt`

[make_log.txt](https://github.com/bigartm/bigartm/files/1509524/make_log.txt)

**Comment by JeanPaulShapo** [comment]
@vladimircape 
Sorry for delay
It seems that there are some inconsistencies between current version of your compiler (`g++`, version 4.9.4) and current version of boost (1.58.0). Could you install the latest version of them available to your distro (e.g. via `apt-get`) and do the same logging stuff again?

**Comment by vladimircape** [comment]
i install latest Boost http://www.boost.org/users/history/version_1_65_1.html
and got more errors
[cmake_log.txt](https://github.com/bigartm/bigartm/files/1517832/cmake_log.txt)
[make_log.txt](https://github.com/bigartm/bigartm/files/1517834/make_log.txt)

**Comment by JeanPaulShapo** [comment]
@vladimircape 
It seems that this guide builds and installs only shared libraries for Boost 1.65.1. In that case you may build `bigartm` executable with shared libraries - just run `cmake -DBUILD_BIGARTM_CLI_STATIC=OFF ..` instead of simple `cmake ..`

**Comment by JeanPaulShapo** [comment]
@vladimircape 
Or you can try to build & install static libraries for Boost. That required one more step during installation:
```bash
sudo ./bootstrap.sh
sudo ./b2 link=static,shared cxxflags="-std=c++11 -fPIC"
sudo ./b2 install
```
instead of
```bash
sudo ./bootstrap.sh
sudo ./b2 install
```

**Comment by vladimircape** [comment]
Thanks i create, but unfortunately after 
sudo make install
i only can use artm only from sudo.
without sudo i can't install

**Comment by JeanPaulShapo** [comment]
@vladimircape Sorry for late answer again
Do you have any conda or virtualenv distribution, and try to use bigartm from there?/
If yes, you can perform the following steps:
```bash
# 1. Activate your conda or virtualenv environment, if necessary
# 2. Go to `python` directory
cd ./python
# 3. Install python package from here via pip
pip install bigartm*.whl
# or
python setup.py install
```
Hope this will help

**Comment by bt2901** [comment]
I'm closing this issue as outdated. 

Currently, BigARTM should be installable via pip on Linux: `pip install bigartm`.

Feel free to reopen this issue if you need to build from source for some reason, or pip installation fails.
