### ISSUE TITLE
artm.version() sometimes returns wrong version number

### ISSUE THREAD

**Issue by bt2901** [bigartm/bigartm#861]
I have a long sequence of installs and reinstalls on my Windows machine (into different Anaconda virtual environments). It seems that some global system variable has stuck at "0.8.0" and haven't updated.

After following the instructions described at http://bigartm.readthedocs.io/en/v0.9.0/devguide/dev_build_windows.html I have this strange situation:

``` 
python -c "import artm; print(artm.version())"
0.8.0
python -c "import pkg_resources; version = pkg_resources.require('bigartm')[0].version; print(version)"
0.9.0
python -c "from artm import SmoothTimeInTopicsPhiRegularizer; print(SmoothTimeInTopicsPhiRegularizer)"
<class 'artm.regularizers.SmoothTimeInTopicsPhiRegularizer'>
```
So, ``artm`` thinks its version is ``0.8.0``, but in reality I had version ``0.9.0`` installed (and 0.9.0-exclusive functionality is available to me)

**Comment by JeanPaulShapo** [comment]
@bt2901 
Actually, there are two version numbers, which you may encounter running BigARTM:
* In first case, `artm.version()` calls `ArtmGetVersion` function from [C interface](https://github.com/bigartm/bigartm/blob/5c2d8b8c411ced91b8de4bbe9c288e0e7ef278a3/src/artm/c_interface.cc#L173). This version is defined [here](https://github.com/bigartm/bigartm/blob/5c2d8b8c411ced91b8de4bbe9c288e0e7ef278a3/src/artm/CMakeLists.txt#L38);
* In the second case, AFAIK you get actual Python API version, which is defined [there](https://github.com/bigartm/bigartm/blob/5c2d8b8c411ced91b8de4bbe9c288e0e7ef278a3/python/setup.py#L137)

I found it very strange to see `0.8.0` version in output, becase we have some other minor versions between `0.8.0` and `0.9.0`. Could you check that you don't use outdated artm.dll?
