### ISSUE TITLE
make fails to build wheel bigartm

### ISSUE THREAD

**Issue by wellywell** [bigartm/bigartm#878]
Environment: Debian GNU/Linux 8 (docker-container from image python:3.6), python3.
All previous steps are completed as in docs/installation/linux.txt.

Make fails at the last step (to build python wheel):

> [100%] Building wheel bigartm
> CMake Error: cmake version 3.0.2
> Usage: /usr/bin/cmake -E [command] [arguments ...]
> Available commands: 
>   chdir dir cmd [args]...   - run command in a given directory
>   compare_files file1 file2 - check if file1 is same as file2
>   copy file destination     - copy file to destination (either file or directory)
>   copy_directory source destination   - copy directory 'source' content to directory 'destination'
>   copy_if_different in-file out-file  - copy file if input has changed
>   echo [string]...          - displays arguments as text
>   echo_append [string]...   - displays arguments as text but no new line
>   environment               - display the current environment
>   make_directory dir        - create a directory
>   md5sum file1 [...]        - compute md5sum of files
>   remove [-f] file1 file2 ... - remove the file(s), use -f to force it
>   remove_directory dir      - remove a directory and its contents
>   rename oldname newname    - rename a file or directory (on one volume)
>   tar [cxt][vfz][cvfj] file.tar [file/dir1 file/dir2 ...]
>                             - create or extract a tar or zip archive
>   sleep <number>...         - sleep for given number of seconds
>   time command [args] ...   - run command and return elapsed time
>   touch file                - touch a file.
>   touch_nocreate file       - touch a file but do not create it.
> Available on UNIX only:
>   create_symlink old new    - create a symbolic link new -> old
> 
> python/CMakeFiles/python_bigartm_wheel.dir/build.make:49: recipe for target 'python/CMakeFiles/python_bigartm_wheel' failed
> make[2]: *** [python/CMakeFiles/python_bigartm_wheel] Error 1
> CMakeFiles/Makefile2:757: recipe for target 'python/CMakeFiles/python_bigartm_wheel.dir/all' failed
> make[1]: *** [python/CMakeFiles/python_bigartm_wheel.dir/all] Error 2
> Makefile:127: recipe for target 'all' failed
> make: *** [all] Error 2

The error occurs when it tries to execute (which seems to be incorrect syntax):
`/usr/bin/cmake -E env ARTM_SHARED_LIBRARY=/opt/myapp/bigartm/build/lib/libartm.so python3 setup.py bdist_wheel -d /opt/myapp/bigartm/build/python`

However it seems to work work after I removed option _-E_, and changed _-d /opt/myapp/bigartm/build/python_ to _-d /opt/myapp/bigartm/python_ in build/python/CMakeFiles/python_bigartm_wheel.dir/build.make.
(or better change the contents of python/CMakelists.txt accordingly).
I am not sure I know what I am doing and the installation happens as it is supposed to.

**Comment by JeanPaulShapo** [comment]
@wellywell 
Yes, you're right - for CMake 3.0.2 this syntax is incorrect.
It seems we have outdated information about required version of CMake.
I have strong opinion this to be 3.1, as stated in [recent PR](https://github.com/bigartm/bigartm/pull/854).
Unfortunately, we haven't completed updating documentation and `CMakeLists.txt` yet.

**Comment by JeanPaulShapo** [comment]
Version inconsistency was fixed in #920
