### ISSUE TITLE
How to enable multithread functionality?

### ISSUE THREAD

**Issue by niwtr** [bigartm/bigartm#889]
Hi, there. 
Using BigARTM on pretty large data (~80MB) on a 24-core Ubuntu server. I think it'd gain better performance with multithread on. I tried to run the test code `/python/tests/wrapper/test_03_concurrency.py` which yields this output: 
```
Iter#0: Perplexity = 6710.208, Time = 0.234
Iter#1: Perplexity = 2434.135, Time = 0.215
Iter#2: Perplexity = 2202.418, Time = 0.192
Iter#3: Perplexity = 1936.493, Time = 0.210
Iter#4: Perplexity = 1774.600, Time = 0.213
Average time per iteration = 0.213
Iter#0: Perplexity = 6710.208, Time = 0.259
Iter#1: Perplexity = 2434.135, Time = 0.250
Iter#2: Perplexity = 2202.418, Time = 0.234
Iter#3: Perplexity = 1936.493, Time = 0.207
Iter#4: Perplexity = 1774.600, Time = 0.211
Average time per iteration = 0.232
Iter#0: Perplexity = 6710.208, Time = 0.228
Iter#1: Perplexity = 2434.135, Time = 0.219
Iter#2: Perplexity = 2202.418, Time = 0.192
Iter#3: Perplexity = 1936.493, Time = 0.218
Iter#4: Perplexity = 1774.600, Time = 0.270
Average time per iteration = 0.226
```

Isn't strange that the average time is nearly the same w/o the multithreading? 
I checked the code and it defines `num_processors_list = [4, 2, 1]` but it's never used. Maybe this test file requires a bug fix. 

Besides that, in my project I've tried setting `num_processors=8`. Snippet: 
```
master = mc.MasterComponent(lib, scores=scores, num_processors=8)
```

Hit `htop` and the CPU usage is around 102%, not significantly different from using a single processor. 
It also performs the same with setting `--threads 8` when using /usr/local/bin/bigartm executable. 

I'm quite confused how to enable the multithreading functionality. Any ideas/suggestions are welcomed. Thanks.

**Comment by ofrei** [comment]
Hi @niwtr 
Thanks for pointing out to concurrency test - indeed, ``num_processors`` hasn't been set (perhaps someone removed it during refactoring). Here is a fix:
https://github.com/bigartm/bigartm/pull/890
On my machine it makes execution time different, e.i. dependent on num_processors.

``--threads`` in bigartm CLI and ``num_processors`` in master component has effect on operations that iterate over batches (e.i. fit_offline, fit_online and transform). Other operations (like gathering/filtering of the dictionary, retrieving phi matrix, etc) are single-threaded. Which operation do you measure? You may also look at the log of the library, and look for ``num_processors`` and ``Processor thread started``:
```
I0308 09:42:54.797955 28020 c_interface.cc:271] Pass MasterModelConfig: topic_name_size=0, score_config_size=2, num_processors=4, pwt_name=pwt, nwt_name=nwt, num_document_passes=0, reuse_theta=no, cache_theta=no, opt_for_avx=yes, disk_cache_path= to ArtmCreateMasterModel
I0308 09:42:54.797955 28020 perplexity.cc:26] Perplexity score calculator created: model_type=0
I0308 09:42:54.798456 28020 c_interface.cc:274] Creating MasterModel (id=1)...
I0308 09:42:54.798456  5860 processor.cc:937] Processor thread started
I0308 09:42:54.798957 16196 processor.cc:937] Processor thread started
I0308 09:42:54.798957 33712 processor.cc:937] Processor thread started
I0308 09:42:54.799455 19872 processor.cc:937] Processor thread started
```

**Comment by ofrei** [comment]
Btw, is there a reason why you use ``MasterComponent`` class? This is an internal implementation detail of BigARTM python API. Our public API is class ``ARTM`` described here:
http://docs.bigartm.org/en/stable/api_references/python_interface/artm_model.html
In this class you set concurrency via ``num_processor`` parameter, in the constructor.

**Comment by niwtr** [comment]
Thanks for your quick reply. 
I've found that the mis-behaviour is caused by num of batch. My original data is assembled in single batch and I guess each processor can only work on one batch at one time so other threads are always idle. All I need is to make num of batch >= num threads. 
It won't easy to find this, let me know if it's true. Thanks!

Answer to your second reply: Because I'm following the example file: `python/tests/wrapper/test_05_multimodal.py`.

**Comment by ofrei** [comment]
Correct, batches should be small enough, and each batch is processed by a single thread. There should be a message in the log - but I'm not sure if this is clearly stated in the documentation.
```
    LOG_FIRST_N(INFO, 1) << "Batches count (=" << args.batch_filename_size()
                         << ") is smaller than num processors (="
                         << instance_->processor_size()
                         << "), which may cause suboptimal performance.";
```

Multimodal topic model are also exposed via ARTM class. There is also a tutorial on this:
http://docs.bigartm.org/en/stable/tutorials/python_userguide/m_artm.html

**Comment by niwtr** [comment]
I didn't see this stated in the doc. Perhaps add it in the future? 
I'm migrating to the new ARTM interface now. It's clearer to use. 
Thanks a lot for your help. -- close!
