### ISSUE TITLE
BigARTM.exe (was: Wrap BigARTM into Vowpal Wabbit CLI)

### ISSUE THREAD

**Issue by romovpa** [bigartm/bigartm#89]
Create command line interface similar to Vowpal Wabbit. The goal is to provide VW.LDA users a way to easily switch to BigARTM.

VW CLI is described here: [slides](https://github.com/JohnLangford/vowpal_wabbit/wiki/lda.pdf), [wiki page](https://github.com/JohnLangford/vowpal_wabbit/wiki/Latent-Dirichlet-Allocation).

**Comment by sashafrey** [comment]
I treat this ticket as a request to implement BigARTM.exe (CLI), described in the following notebook:
http://nbviewer.ipython.org/github/bigartm/bigartm-book/blob/master/junk/cli/BigARTM_CommandLineInferface.ipynb
This enhancement is the main deliverable for BigARTM v0.7.2 milestone.

**Comment by sashafrey** [comment]
Fixed by https://github.com/bigartm/bigartm/pull/280
