### ISSUE TITLE
Examples for SmoothTimeInTopicsPhiRegularizer

### ISSUE THREAD

**Issue by qthurier** [bigartm/bigartm#901]
I assume this reguarizer aims to do dynamic topic modeling. Where can I find documentation/examples describing how to use it?

**Comment by fkrasnov** [comment]
Hi, 
Try this one 
http://nbviewer.jupyter.org/github/bigartm/bigartm-book/blob/master/ARTM_tutorial_EN.ipynb
--
Fedor

**Comment by qthurier** [comment]
I don't think this tutorial use SmoothTimeInTopicsPhiRegularizer, unless I missed something?

**Comment by MelLain** [comment]
Hi! I'm sorry, but there's no tutorial on this regularizer yet( Though it's idea and usage are very simple: it only smooths the neighbor values in one topic, e.g. if you have in your Phi matrix (in the given rows order), it will work in following way

p_wt \propto n_wt + tau * p_wt * (sign(p_{w-1,t} - p_wt) + sign(p_{w+1,t} - p_wt))

To use properly you should:
1) choose the modality of time (or smth like it) and set it into class_id parameter of the regularizer
2) create your model from a Dictionary, that was built with vocab file (see Dictionary doc), in which your specified all tokens, you want to see in the model in order you need. For this regularizer you need to put all tokens of time modality in the lexicographical order (as you need to smooth neighbor moments of time).

**Comment by qthurier** [comment]
Thanks for your reply @MelLain. So if I want to do topic modeling over a modality author*time my input data should look like that ?

`
doc_0|@default_class foo:1 bar:2 baz:3 qux:4|@timestamp_class John_2018-01
doc_1|@default_class foo:4 bar:1 baz:2 qux:3|@timestamp_class John_2018-02
doc_2|@default_class foo:3 bar:4 baz:1 qux:2|@timestamp_class John_2018-03
doc_3|@default_class foo:2 bar:3 baz:4 qux:1|@timestamp_class John_2018-04
doc_4|@default_class foo:1 bar:2 baz:3 qux:4|@timestamp_class John_2018-05
doc_5|@default_class foo:4 bar:1 baz:2 qux:3|@timestamp_class John_2018-06
doc_6|@default_class foo:3 bar:4 baz:1 qux:2|@timestamp_class Jack_2018-01
doc_7|@default_class foo:2 bar:3 baz:4 qux:1|@timestamp_class Jack_2018-02
doc_8|@default_class foo:1 bar:2 baz:3 qux:4|@timestamp_class Jack_2018-03
doc_9|@default_class foo:4 bar:1 baz:2 qux:3|@timestamp_class Jack_2018-04
doc_10|@default_class foo:3 bar:4 baz:1 qux:2|@timestamp_class Jack_2018-05
doc_11|@default_class foo:2 bar:3 baz:4 qux:1|@timestamp_class Jack_2018-06
`

How to constraint the model so that John_2018-06 is not consider as the neighbor of Jack_2018-01?

**Comment by MelLain** [comment]
There's no matter in order of your timestamps in vowpal wabbit file. You need to create a vocab file, text file, where each line has format <token class_id>, the order of tokens in this file is the order of tokens in your model. You need smth like
John_2018-01 @timestamp_class
John_2018-02 @timestamp_class
John_2018-03 @timestamp_class
John_2018-04 @timestamp_class
John_2018-05 @timestamp_class
John_2018-06 @timestamp_class
John_2018-07 @timestamp_class
...

Don't forget, that this file must contain all tokens of all class_ids you want to use in the model, including `@default_class`

This file should be passed in `Dictionary.gather()` method, and generated Dictionary should be used as `dictionary` parameter in constructor `artm.ARTM`. You can extract your model via get_phi method and check the order of tokens.
