### ISSUE TITLE
Install error macos "dyld: Symbol not found"

### ISSUE THREAD

**Issue by qthurier** [bigartm/bigartm#902]
I get this error after calling make. I'm using mac os 10.13.4.

[ 72%] Generating headers and sources from *.proto files
dyld: Symbol not found: __ZNSt3tr18__detail12__prime_listE
  Referenced from: /Users/quentint/dev/bigartm/build/bin/protoc (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libstdc++.6.0.9.dylib

Any idea how to fix that?

**Comment by bt2901** [comment]
I'm closing this issue as outdated. 

We have provisional pre-built wheel files for Mac on PyPi. I suggest installing the library with pip: `pip install -i https://test.pypi.org/simple/ bigartm` (and this problem will hopefully be fixed here). 

If I am wrong and this issue still persists on pre-built wheel, or for some reason installation with pip isn't ideal for you (or doesn't work), feel free to re-open this.
