### ISSUE TITLE
Some bigartm.INFO files

### ISSUE THREAD

**Issue by twelveth** [bigartm/bigartm#919]
While working in jupyter notebook, artm constantly creates some kind of "**bigartm (n).INFO**" files (**n** is the number of file). Currently I already have 47 of them, and its number grows.

Btw, I shutdown all jupyter kernels, but these files are still being generated.

**Fedora 28. python 3.6.5**

**Comment by ofrei** [comment]
I assume these might be log files generated by bigartm core module. They contain useful diagnostic information, so in general it is recommended to keep them. If you want to turn off logging:
```
import artm
lc = artm.messages.ConfigureLoggingArgs()
lc.minloglevel=2  # 0 = INFO, 1 = WARNING, 2 = ERROR, 3 = FATAL
# when pass lc to constructor you may also change log location like this:  lc.log_dir=r'C:\bigartm_log'
lib = artm.wrapper.LibArtm(logging_config=lc)
```
or
```
# To change any other logging parameters at runtime (except logging folder which must be set once in constructore before any other calls to artm lib) 
lib.ArtmConfigureLogging(lc)
```

**Comment by ofrei** [comment]
Does this fix your issue?

**Comment by twelveth** [comment]
Yeah, I've found it later in FAQ and C Interface. The main problem is that these files are generated in large quantity (even when all kernels are shutdown) instead of being rewriten. I've rebooted OS, and they are still being generated.

**Comment by kuraga** [comment]
@ofrei , couldn't be fixed by setting some environment variables?
