### ISSUE TITLE
Gensim interface

### ISSUE THREAD

**Issue by romovpa** [bigartm/bigartm#92]
Implement algorithms based on BigARTM as a [gensim](http://radimrehurek.com/gensim/) model.
See [experiments on the English Wikipedia](http://radimrehurek.com/gensim/wiki.html).

BigARTM interface could look like this:
```
model = gensim.models.bigartm.RobustPLSA(corpus=mm, id2word=id2word, num_topics=100, update_every=1, chunksize=10000, passes=1)
model = gensim.models.bigartm.ARTM(corpus=mm, id2word=id2word, regularizers=[...], num_topics=100, passes=1)
...
```

**Comment by sashafrey** [comment]
I think this will be covered by ArtmModel (https://github.com/bigartm/bigartm/pull/228)

**Comment by sashafrey** [comment]
Actually, it is up to submitter to close the ticket. Is there any work except #228 to be done regarding this ticket? If so, I suggest we just close this ticket.

**Comment by sashafrey** [comment]
I think this is covered by new ARTM interface
http://nbviewer.ipython.org/github/bigartm/bigartm-book/blob/master/BigARTM_example_RU.ipynb
