### ISSUE TITLE
macOS build fail while Scanning dependencies of target gflags-static

### ISSUE THREAD

**Issue by evyak** [bigartm/bigartm#926]
I'm trying to build the library using standard tutorial on my machine

- masOS 10.13.6 
- cmake 3.12.1

I get following error when I'm trying to generate a makefile via cmake .. within the build/ directory.

```
Scanning dependencies of target gflags-static
[  1%] Building CXX object 3rdparty/gflags/CMakeFiles/gflags-static.dir/src/gflags.cc.o
In file included from /Users/<username>/bigartm/3rdparty/gflags/src/gflags.cc:112:
/Users/<username>/bigartm/3rdparty/gflags/src/util.h:264:12: error: use of undeclared identifier 'mkdir'
        int err = mkdir(path->c_str(), 0755);
                  ^
/Users/<username>/bigartm/3rdparty/gflags/src/util.h:267:3: error: use of undeclared identifier 'mkdir'
  mkdir("/tmp/gflags_unittest", 0755);
  ^
2 errors generated.
make[2]: *** [3rdparty/gflags/CMakeFiles/gflags-static.dir/src/gflags.cc.o] Error 1
make[1]: *** [3rdparty/gflags/CMakeFiles/gflags-static.dir/all] Error 2
make: *** [all] Error 2
```

Could you please help me with this problem.

**Comment by MichaelSolotky** [comment]
Hi, @evyak
Could you please try to compile the latest master version? We've added some changes in build system with AppleClang. I hope it'll help. Also, have you installed all the dependencies from the tutorial?

**Comment by RmDr** [comment]
Hi, @MichaelSolotky 
I had the same problem on macOS 10.14.2 using --stable branch. I compiled master branch and it has worked.
Thank you!

**Comment by bt2901** [comment]
I'm closing this issue as outdated. 

We have provisional pre-built wheel files for Mac on PyPi. I suggest installing the library with pip: `pip install -i https://test.pypi.org/simple/ bigartm` (and this problem will hopefully be fixed here). 

If I am wrong and this issue still persists on pre-built wheel, or for some reason installation with pip isn't ideal for you (or doesn't work), feel free to re-open this.
