### ISSUE TITLE
appveyor CI build is failing

### ISSUE THREAD

**Issue by ofrei** [bigartm/bigartm#933]
```
error: failed to prepare transaction (could not satisfy dependencies)
:: installing mingw-w64-x86_64-gcc (8.2.0-3) breaks dependency 'mingw-w64-x86_64-gcc=8.2.0-1' required by mingw-w64-x86_64-gcc-ada
```

**Comment by ofrei** [comment]
@MelLain @JeanPaulShapo @MichaelSolotky do you know anything about appveyor failures?

**Comment by MichaelSolotky** [comment]
Here are some solutions to the similar trouble that I'm going to check
https://github.com/Alexpux/MSYS2-packages/issues/1190

**Comment by MichaelSolotky** [comment]
@ofrei 
This worked out, here's what needed to be changed: https://github.com/bigartm/bigartm/pull/941/files
