### ISSUE TITLE
make install fails on ubuntu: No module named setuptools

### ISSUE THREAD

**Issue by Jcerwin** [bigartm/bigartm#942]
I initially installed the BigARTM python package on Ubuntu 18.04 following the  <a  href='https://bigartm.readthedocs.io/en/stable/installation/linux.html#script-to-install-bigartm-on-ubuntu'>installation guidance</a>. I skipped the full installation and used the  ` alternative step 4 - installing only the Python package`. The python package works great. However, any additional attempts to install the full installation do not work.

Please note that the latest version of __setuptools__ is installed and can be referenced and used in a python program.  

```
sudo make install
[sudo] password for john: 
[  2%] Built target gflags-static
[  4%] Built target google-glog
[ 12%] Built target libprotobuf-lite
[ 39%] Built target libprotobuf
[ 71%] Built target libprotoc
[ 72%] Built target protoc
[ 72%] Built target proto_generation
[ 73%] Built target internals_proto
[ 74%] Built target messages_proto
[ 91%] Built target artm-static
[ 91%] Built target artm
[ 98%] Built target artm_tests
[ 99%] Built target bigartm
[ 99%] Building python package bigartm
Traceback (most recent call last):
  File "/home/john/bigartm/python/setup.py", line 3, in <module>
    from setuptools import setup, find_packages, Distribution
ImportError: No module named setuptools
python/CMakeFiles/python_bigartm_build.dir/build.make:57: recipe for target 'python/CMakeFiles/python_bigartm_build' failed
make[2]: *** [python/CMakeFiles/python_bigartm_build] Error 1
CMakeFiles/Makefile2:823: recipe for target 'python/CMakeFiles/python_bigartm_build.dir/all' failed
make[1]: *** [python/CMakeFiles/python_bigartm_build.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by bt2901** [comment]
I'm closing this issue as outdated. 

Currently, BigARTM should be installable via pip: `pip install bigartm`. At least, for Linux.

Feel free to reopen this issue if you need to build from source for some reason, or pip installation fails.
