### ISSUE TITLE
No releases for a while

### ISSUE THREAD

**Issue by shayantabrizi** [bigartm/bigartm#945]
Does the fact that no release is made since Nov 5, 2017 mean that everything commited afterwards is unstable?

**Comment by ofrei** [comment]
@shayantabrizi Hi, and thanks for asking!
The biggest concern is T-ARTM (transactions functionality), which is a big new feature that touches core functionality. I were still waiting for confirmation that it had been fully tested. @MelLain do you know the status on T-ARTM? Is it stable enough to release new bigartm version?

**Comment by shayantabrizi** [comment]
So, if we do not need new features, is there any critical bug fix since the latest release? Or we can continue using it?

**Comment by bt2901** [comment]
As a follow-up to this, we will be maintaining two versions (0.9.x and 0.10.x) of BigARTM in parallel.

If you need need transactions functionality, then it makes sense to update to `0.10.1`, but note that it could be unstable at the moment. If you don't need transactions functionality, then you would be safe updating to `0.9.2`.
