### ISSUE TITLE
BigARTM for Mac os X Step 3. Build and install BigARTM library

### ISSUE THREAD

**Issue by ilyaio** [bigartm/bigartm#951]
On step 3 I received the following message:
MacBook-Pro-ilya:~ ilyaivanov$ cd bigartm && mkdir build && cd build
MacBook-Pro-ilya:build ilyaivanov$ cmake ..
-- The C compiler identification is AppleClang 10.0.0.10001044
-- The CXX compiler identification is AppleClang 10.0.0.10001044
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build type: Release
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Boost version: 1.68.0
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Boost version: 1.68.0
-- Found the following Boost libraries:
--   thread
--   program_options
--   date_time
--   filesystem
--   iostreams
--   system
--   chrono
--   timer
--   atomic
--   regex
CMake Warning (dev) at 3rdparty/gflags/CMakeLists.txt:39 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'BUILD_SHARED_LIBS'.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at 3rdparty/gflags/CMakeLists.txt:40 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'BUILD_STATIC_LIBS'.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at 3rdparty/gflags/CMakeLists.txt:41 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'BUILD_gflags_LIB'.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at 3rdparty/gflags/CMakeLists.txt:42 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'BUILD_gflags_nothreads_LIB'.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for C++ include stdint.h
-- Looking for C++ include stdint.h - found
-- Looking for C++ include inttypes.h
-- Looking for C++ include inttypes.h - not found
-- Looking for C++ include sys/types.h
-- Looking for C++ include sys/types.h - not found
-- Looking for C++ include sys/stat.h
-- Looking for C++ include sys/stat.h - not found
-- Looking for C++ include fnmatch.h
-- Looking for C++ include fnmatch.h - not found
-- Looking for strtoll
-- Looking for strtoll - not found
-- Looking for strtoq
-- Looking for strtoq - not found
-- Looking for C++ include stddef.h
-- Looking for C++ include stddef.h - found
-- Check size of pthread_rwlock_t
-- Check size of pthread_rwlock_t - failed
-- running mz compiler detection tools
-- compiler is clang
-- GCC compatible compiler found
-- compiler version Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
-- C++11 support detected
-- 64bit platform
-- Today is: пн, 18 фев 2019 00:20:28 +0300

-- forcing C++11 support on this platform
-- configuring for build type: Release
-- Looking for include file dlfcn.h
-- Looking for include file dlfcn.h - found
-- Looking for include file execinfo.h
-- Looking for include file execinfo.h - found
-- Looking for include file glob.h
-- Looking for include file glob.h - found
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for include file libunwind.h
-- Looking for include file libunwind.h - found
-- Looking for include file libunwind.h
-- Looking for include file libunwind.h - found
-- Looking for include file gflags/gflags.h
-- Looking for include file gflags/gflags.h - not found
-- Looking for include file memory.h
-- Looking for include file memory.h - found
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for include file pwd.h
-- Looking for include file pwd.h - found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file strings.h
-- Looking for include file strings.h - found
-- Looking for include file syscall.h
-- Looking for include file syscall.h - not found
-- Looking for include file syslog.h
-- Looking for include file syslog.h - found
-- Looking for include file sys/call.h
-- Looking for include file sys/call.h - not found
-- Looking for include file sys/time.h
-- Looking for include file sys/time.h - found
-- Looking for include file sys/syscall.h
-- Looking for include file sys/syscall.h - found
-- Looking for include file sys/ucontext.h
-- Looking for include file sys/ucontext.h - found
-- Looking for include file sys/utsname.h
-- Looking for include file sys/utsname.h - found
-- Looking for include file ucontext.h
-- Looking for include file ucontext.h - not found
-- Looking for include file unwind.h
-- Looking for include file unwind.h - found
-- Looking for fcntl
-- Looking for fcntl - found
-- Looking for sigaltstack
-- Looking for sigaltstack - found
-- Looking for __builtin_expect
-- Looking for __builtin_expect - not found
-- Looking for __sync_val_compare_and_swap
-- Looking for __sync_val_compare_and_swap - not found
CMake Warning (dev) at 3rdparty/protobuf-3.0.0/cmake/CMakeLists.txt:15 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'protobuf_BUILD_TESTS'.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at 3rdparty/protobuf-3.0.0/cmake/install.cmake:41 (message):
  The file
  "/Users/ilyaivanov/bigartm/3rdparty/protobuf-3.0.0/src/google/protobuf/repeated_field_reflection.h"
  is listed in
  "/Users/ilyaivanov/bigartm/3rdparty/protobuf-3.0.0/cmake/cmake/extract_includes.bat.in"
  but there not exists.  The file will not be installed.
Call Stack (most recent call first):
  3rdparty/protobuf-3.0.0/cmake/CMakeLists.txt:159 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Found GLOG: /Users/ilyaivanov/bigartm/3rdparty/glog/src  
-- Boost version: 1.68.0
-- Found the following Boost libraries:
--   thread
--   program_options
--   date_time
--   filesystem
--   iostreams
--   system
--   chrono
--   timer
--   atomic
--   regex
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/ilyaivanov/bigartm/build
MacBook-Pro-ilya:build ilyaivanov$ make
Scanning dependencies of target gflags-static
[  1%] Building CXX object 3rdparty/gflags/CMakeFiles/gflags-static.dir/src/gflags.cc.o
In file included from /Users/ilyaivanov/bigartm/3rdparty/gflags/src/gflags.cc:112:
/Users/ilyaivanov/bigartm/3rdparty/gflags/src/util.h:264:12: error: use of
      undeclared identifier 'mkdir'
        int err = mkdir(path->c_str(), 0755);
                  ^
/Users/ilyaivanov/bigartm/3rdparty/gflags/src/util.h:267:3: error: use of
      undeclared identifier 'mkdir'
  mkdir("/tmp/gflags_unittest", 0755);
  ^
2 errors generated.
make[2]: *** [3rdparty/gflags/CMakeFiles/gflags-static.dir/src/gflags.cc.o] Error 1
make[1]: *** [3rdparty/gflags/CMakeFiles/gflags-static.dir/all] Error 2
make: *** [all] Error 2
MacBook-Pro-ilya:build ilyaivanov$ sudo make install
Password:
[  1%] Building CXX object 3rdparty/gflags/CMakeFiles/gflags-static.dir/src/gflags.cc.o
In file included from /Users/ilyaivanov/bigartm/3rdparty/gflags/src/gflags.cc:112:
/Users/ilyaivanov/bigartm/3rdparty/gflags/src/util.h:264:12: error: use of
      undeclared identifier 'mkdir'
        int err = mkdir(path->c_str(), 0755);
                  ^
/Users/ilyaivanov/bigartm/3rdparty/gflags/src/util.h:267:3: error: use of
      undeclared identifier 'mkdir'
  mkdir("/tmp/gflags_unittest", 0755);
  ^
2 errors generated.
make[2]: *** [3rdparty/gflags/CMakeFiles/gflags-static.dir/src/gflags.cc.o] Error 1
make[1]: *** [3rdparty/gflags/CMakeFiles/gflags-static.dir/all] Error 2
make: *** [all] Error 2

Please, proposed any advice

**Comment by bt2901** [comment]
I'm closing this issue as outdated. 

We have provisional pre-built wheel files for Mac on PyPi. I suggest installing the library with pip: `pip install -i https://test.pypi.org/simple/ bigartm` (and this problem will hopefully be fixed here). 

If I am wrong and this issue still persists on pre-built wheel, or for some reason installation with pip isn't ideal for you (or doesn't work), feel free to re-open this.
