### ISSUE TITLE
ARTM dump and load methods don't work correctly

### ISSUE THREAD

**Issue by MichaelSolotky** [bigartm/bigartm#953]
Operations of damping and then loading a model give another model with incomplete Phi mathix, as a result, the total number of tokens decreases and columns of Phi don't sum into 1.
![photo_2019-03-08_17-30-28](https://user-images.githubusercontent.com/25284863/54034437-e4892000-41c7-11e9-96c7-a913152ead33.jpg)

**Comment by vseledkin** [comment]
It seems like I facing the same problem, as a result transform for new documents produces poor results, any plans to fix it? Since development process is very slow may be someone have insight how to "workaround it" may be through save/load matrices manually or something like that...
