### ISSUE TITLE
BigArtm trouble

### ISSUE THREAD

**Issue by StaryRavin** [bigartm/bigartm#954]
I cant't install bigartm on my macbook air. There are lots of mistakes after *make* and bigartm doesn't work. Please help!

**Comment by bt2901** [comment]
I'm closing this issue as outdated. 

We have provisional pre-built wheel files for Mac on PyPi. I suggest installing the library with pip: `pip install -i https://test.pypi.org/simple/ bigartm` (and this problem will hopefully be fixed here). 

If I am wrong and this issue still persists on pre-built wheel, or for some reason installation with pip isn't ideal for you (or doesn't work), feel free to re-open this.
