### ISSUE TITLE
Logical Error at python API  model get_phi_sparse method

### ISSUE THREAD

**Issue by vseledkin** [bigartm/bigartm#958]
Syntactically it is correct, but i think you want to maintain list of pairs instead of listing the result of checking particular pair availability amongst ... and c is not defined of course

https://github.com/bigartm/bigartm/blob/955bb092b8cb9e7676fae05500ba88233c41be50/python/artm/artm_model.py#L852

```bash
 File "/usr/local/lib/python3.6/site-packages/artm/artm_model.py", line 851, in get_phi_sparse
    rows = [(c, t) in zip(tm.token, tm.class_id)]
NameError: name 'c' is not defined
```

fix 

```python
rows = [(c, t) for (c, t) in zip(tm.token, tm.class_id)]
```

sorry for no PR my fork is not compatible

**Comment by ofrei** [comment]
Ouch, that's not good. @vseledkin thanks for pointing this out!

**Comment by rustameo** [comment]
Hello, stable branch still contains the bug. I installed it, so I was very surprised when I saw that everything is ok on the master branch.
