### ISSUE TITLE
не работает! Dont work

### ISSUE THREAD

**Issue by ALexanderBorisovsky** [bigartm/bigartm#963]
На последнем этапе установки выползает такая ошибка

bigartm alexaky$ echo /usr/local/lib | sudo tee /etc/ld.so.conf.d/artm.conf
tee: /etc/ld.so.conf.d/artm.conf: No such file or directory
/usr/local/lib

**Comment by Zzema** [comment]
Та же ошибка(

**Comment by bt2901** [comment]
А что за ОС?

**Comment by Zzema** [comment]
> А что за ОС?

Mac OS 10.14.6
Пошел обходным путем, установил этот модуль через гугл колаб. Нужно для выполнения задания, на своем компе так и не разобрался как запустить в итоге этот artm
