### ISSUE TITLE
MacOS Mojave 10.14.6 compatibility v0.10.0

### ISSUE THREAD

**Issue by EugeniaVeselova** [bigartm/bigartm#977]
While installing artm I have many warnings related to 10.12 version without errors and "No module named <artm>" finally. 

Warnings example:
/Users/xtonev/bigartm/3rdparty/protobuf-3.0.0/src/google/protobuf/stubs/atomicops_internals_macosx.h:68:10: warning: 
      'OSAtomicAdd32' is deprecated: first deprecated in macOS 10.12 - Use
      std::atomic_fetch_add_explicit(std::memory_order_relaxed) from <atomic>
      instead [-Wdeprecated-declarations]
  return OSAtomicAdd32(increment, const_cast<Atomic32*>(ptr));

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/libkern/OSAtomicDeprecated.h:749:9: note: 
      'OSMemoryBarrier' has been explicitly marked deprecated here
void    OSMemoryBarrier( void );

Python version 3.7

**Comment by bt2901** [comment]
I'm closing this issue as outdated. 

We have provisional pre-built wheel files for Mac on PyPi. I suggest installing the library with pip: `pip install -i https://test.pypi.org/simple/ bigartm` (and this problem will hopefully be fixed here). 

If I am wrong and this issue still persists on pre-built wheel, or for some reason installation with pip isn't ideal for you (or doesn't work), feel free to re-open this.
