### ISSUE TITLE
Decreasing num_processors doesn't free resources

### ISSUE THREAD

**Issue by bt2901** [bigartm/bigartm#978]
Steps to reproduce:

* set num_processors to something big
* run fit_offline, observe (e.g. via htop) several threads working on different cores
* no resources are freed when fit_offline is finished
* set num_processors=1. Expected behavior: resources are returned to the system. Actual behavior: nope.

I investigated this problem for a bit. I think the culprit is that `Processor::~Processor() ` is never called. The destructor probably should be invoked in Instance::CreateOrReconfigureRegularizer:

```
    // Adjust size of processors_; cast size to int to avoid compiler warning.
    while (static_cast<int>(processors_.size()) > target_processors_count) {
      processors_.pop_back();
    }
```
since the type of `processors_` is `  std::vector<std::shared_ptr<Processor> > processors_;`. 

For some reason it seems that the garbage collection never occurs.

**Comment by ofrei** [comment]
@bt2901 Can't reproduce this. Here is my change to one of bigartm native tests:
https://github.com/ofrei/bigartm/commit/b681ff12e7ed87e2c3c3298db802235fbf620c90
then I monitor number of threads in the process and it is correct:
```
(base) oleksanf@mach:~/github/bigartm/bigartm/build/bin$ cat /proc/26460/status  | grep Threads
Threads:        3
(base) oleksanf@mach:~/github/bigartm/bigartm/build/bin$ cat /proc/26460/status  | grep Threads
Threads:        101
(base) oleksanf@mach:~/github/bigartm/bigartm/build/bin$ cat /proc/26460/status  | grep Threads
Threads:        2
```

Destuctor Processors::~Processor() should produce the following message in the log, could you please check if these are present on your system?
```
I0807 19:51:25.370508 26488 processor.cc:66] Processor thread stopped
```

**Comment by bt2901** [comment]
This issue turned out to be more complicated that it appeared. Breaking it down:

* I observe the same behaviour of tests as you.
* However, it doesn't seem to work inside Jupyter notebook (I think it invokes destructor according to log, but the number of threads does not decrease).
* However, this turned out to be irrelevant, since Jupyter does wacky things with RAM usage anyways. It interferes with Python's garbage collection by keeping some references to the deleted objects if they are related to output variables.
* After that, I started investigating RAM and CPU consumption and whether invoking `model.dispose()` is helpful in that regard. My experiment was as follows: create 20 PLSA models, dispose all of them, repeat the process three times while keeping track of resources. The result: it is somewhat helpful, but it isn't quite what I hoped for.
* The explanation: "The reason is CPython's memory management. The way Python manages memory make it hard for long running programs. When you explicitly free an object with del statement, CPython necessarily does not return allocated memory to the OS. It keeps the memory for further use in future. One way to work this problem around is to use Multiprocessing module and kill the process after you are done with the job and create another one."

So, what's the takeaway message? Looks like you should delegate "heavy-lifting" to the child process, save the results and then reclaim the child's resources. It should solve a lot of problems.

There is nothing to report yet, but our team is looking into this.

**Comment by bt2901** [comment]
For posterity.

I used this script to test resources consumption:

```
import psutil, os
from time import sleep

def memory_info():
    info = psutil.Process(os.getpid()).memory_full_info()

    print('USS : {:>6.2f}'.format(info.uss / 10 ** 6))
    print('RSS : {:>6.2f}'.format(info.rss / 10 ** 6))
    print('VMS : {:>6.2f}'.format(info.vms / 10 ** 6))
    print('DATA: {:>6.2f}'.format(info.data / 10 ** 6))


import artm

dictionary_sci = artm.Dictionary()
dictionary_sci.load("dict.dict")

def create_bare_models():
    for _ in range(20):
        sleep(2)
        model_artm = artm.ARTM(
            num_topics=201,
            num_processors=3,
            theta_columns_naming='title',
            show_progress_bars=False,
            class_ids={"@word": 1},
            dictionary=dictionary_sci
        )
        models.append(model_artm)
    return models


def dispose_all_models(models):
    for i in range(20):
        sleep(2)
        model_artm = models[i]
        try:
            # s = model_artm.master
            # s._lib.ArtmDisposeModel(s.master_id, model_artm.model_pwt)
            # s._lib.ArtmDisposeModel(s.master_id, model_artm.model_nwt)
            model_artm.dispose()
        except AttributeError:
            pass
    import gc
    gc.collect()

sleep(5)

models = []

print()
print("before creating models")
memory_info()

def one_cycle():
    models = create_bare_models()

    print("\n after creating models")
    memory_info()

    sleep(5)

    dispose_all_models(models)

    print("\n after disposing of models")

    memory_info()
    sleep(5)

one_cycle()
one_cycle()
one_cycle()
```

Then. with help of `psrecord`, I produced this interesting plot:
```
#!/bin/bash    
psrecord $(pgrep -f "mem_test.py") --interval 1 --duration 200 --include-children --plot plot.png
wait $P1 
echo 'Done'
```
![image](https://user-images.githubusercontent.com/3958256/66346307-92290100-e95a-11e9-966f-0344a0ea64c0.png)
