### ISSUE TITLE
Installation problem MAC

### ISSUE THREAD

**Issue by vnomy** [bigartm/bigartm#992]
Hello!

Follow the instructions http://docs.bigartm.org/en/stable/installation/linux.html#
On the line cmake .. the mistake occurs. Logs attached.
Please help. Thanks in advance.
[CMakeError.log](https://github.com/bigartm/bigartm/files/3982290/CMakeError.log)
[CMakeOutput.log](https://github.com/bigartm/bigartm/files/3982291/CMakeOutput.log)

**Comment by anastasiyapavlovskaya** [comment]
Had the same issue. This helped: https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a

**Comment by bt2901** [comment]
I'm closing this issue as outdated. 

We have provisional pre-built wheel files for Mac on PyPi. I suggest installing the library with pip: `pip install -i https://test.pypi.org/simple/ bigartm` (and this problem will hopefully be fixed here). 

If I am wrong and this issue still persists on pre-built wheel, or for some reason installation with pip isn't ideal for you (or doesn't work), feel free to re-open this.
